-- DEPRECATED: Do not use this file for seeding products.
-- It previously inserted 15 fake demo medicines for Razorpay review (removed).
--
-- Use real chemist inventory instead:
--   1. remove_demo_products.sql  — purge mock products from DB
--   2. upload_chemist_db.sql     — load real MRP + stock from chemist CSV
--
-- Generated from: database by chemist .csv
