-- Massive DB Insert generated from CSV (Duplicates Merged)
INSERT INTO public.products (id, name, brand, category, price, "desc", icon, unit, popular, stock)
VALUES 
  (gen_random_uuid(), 'ISOJET 10MG CAP 10''S', '', 'Medicines', 118, '', 'ti-pill', '10''S', false, 2),
  (gen_random_uuid(), 'ROSACEA SOAP 75 GM', '', 'Skin Care', 134, '', 'ti-spray', '75GM', false, 1),
  (gen_random_uuid(), 'BANDY PLUS BOTTLE OF 10ML SUSPENSION', '', 'Stationery', 42, '', 'ti-pill', '10ML', false, 1),
  (gen_random_uuid(), 'COMBIHALE FF 250 REDICAPS 30BOX', '', 'Medicines', 478, '', 'ti-pill', '30BOX', false, 3),
  (gen_random_uuid(), 'FUCIBET CREAM 15GM 15GM', '', 'Skin Care', 98, '', 'ti-spray', '15GM', false, 1),
  (gen_random_uuid(), 'ZEVITON SYP-200ML - 200  ML', '', 'Medicines', 151, '', 'ti-pill', '200  ML', false, 2),
  (gen_random_uuid(), 'KETO SOAP 50GM 50GM', '', 'Skin Care', 133, '', 'ti-spray', '50GM', false, 2),
  (gen_random_uuid(), 'KETO SOAP 100GM 100GM', '', 'Skin Care', 283, '', 'ti-spray', '100GM', false, 1),
  (gen_random_uuid(), 'O2 TAB STRIP 10''S', '', 'Medicines', 195, '', 'ti-pill', '10''S', false, 2),
  (gen_random_uuid(), 'ENERZAL ZERO ORANGE FLAVOUR BOTTLE OF 400ML LIQUID', '', 'Vitamins', 77, '', 'ti-pill', '400ML', false, 4),
  (gen_random_uuid(), 'GLYCIPHAGE VG1 TAB 10''S', '', 'Medicines', 138, '', 'ti-pill', '10''S', false, 6),
  (gen_random_uuid(), 'NEERI SYRUP 100ML', '', 'Cold & Flu', 154, '', 'ti-bottle', '100ML', false, 1),
  (gen_random_uuid(), 'DEN TONIC PILL 10GM', '', 'Medicines', 76, '', 'ti-pill', '10GM', false, 10),
  (gen_random_uuid(), 'KETZ SOAP 75GM', '', 'Skin Care', 110, '', 'ti-spray', '75GM', false, 1),
  (gen_random_uuid(), 'THYRONORM 50MCG TAB 120``S 120`S', '', 'Medicines', 132, '', 'ti-pill', '120`S', false, 3),
  (gen_random_uuid(), 'ENERZAL PET ORANGE LIQUID 400 ML', '', 'Vitamins', 57, '', 'ti-pill', '400ML', false, 16),
  (gen_random_uuid(), 'BONABONA -XT - 15CAP', '', 'Medicines', 364, '', 'ti-pill', '15CAP', false, 1),
  (gen_random_uuid(), 'CUFDOZ AD SYP - 100ML', '', 'Medicines', 117, '', 'ti-pill', '100ML', false, 5),
  (gen_random_uuid(), 'DEPLATT A 75MG STRIP OF 15 TABLETS', '', 'Medicines', 121, '', 'ti-pill', '15 NO''S', false, 3),
  (gen_random_uuid(), 'NOVASTAT 10MG TAB 15`S', '', 'Medicines', 383, '', 'ti-pill', '15`S', false, 3),
  (gen_random_uuid(), 'VILDAPRIDE M 50/500MG TAB - 15TAB', '', 'Medicines', 178, '', 'ti-pill', '15TAB', false, 6),
  (gen_random_uuid(), 'VILPOWER M 500MG TABLET 10''S', '', 'Medicines', 178, '', 'ti-pill', '10''S', false, 3),
  (gen_random_uuid(), 'CABGOLIN 0.5MG TABLET 4''S', '', 'Medicines', 515, '', 'ti-pill', '4''S', false, 1),
  (gen_random_uuid(), 'CALADRYL SKIN ALLERGY LOTION FOR ALL SKIN TYPES - 125ML', '', 'Skin Care', 109, '', 'ti-spray', '125ML', false, 2),
  (gen_random_uuid(), 'TAZLOC AM 40MG STRIP OF 10 TABLETS', '', 'Medicines', 150, '', 'ti-pill', '10''S', false, 2),
  (gen_random_uuid(), 'BETNOVATE GM CREAM - 20GM', '', 'Skin Care', 47, '', 'ti-spray', '20GM', false, 10),
  (gen_random_uuid(), 'BETNOVATE C CREAM 30GM', '', 'Skin Care', 73, '', 'ti-spray', '30 G', false, 10),
  (gen_random_uuid(), 'REXIDIN M FORTE GEL 15GM', '', 'Pain Relief', 93, '', 'ti-pill', '15GM', false, 3),
  (gen_random_uuid(), 'OVRAL G TABLET 20''S', '', 'Medicines', 344, '', 'ti-pill', '20''S', false, 2),
  (gen_random_uuid(), 'OVRAL L STRIP OF 21 TABLETS', '', 'Medicines', 68, '', 'ti-pill', '21''S', false, 10),
  (gen_random_uuid(), 'TELMIDUCE AM TAB 10''S', '', 'Medicines', 76, '', 'ti-pill', '10''S', false, 14),
  (gen_random_uuid(), 'MAHACEF CV 200MG TAB 6`S', '', 'Medicines', 186, '', 'ti-pill', '6`S', false, 2),
  (gen_random_uuid(), 'SOMPRAZ D 40MG CAP 15''S', '', 'Medicines', 263, '', 'ti-pill', '15''S', false, 1),
  (gen_random_uuid(), 'LIPIROSE 20MG TABLET 10''S', '', 'Medicines', 249, '', 'ti-pill', '10''S', false, 2),
  (gen_random_uuid(), 'VETORY SP TABLET 10''S', '', 'Medicines', 68, '', 'ti-pill', '10''S', false, 2),
  (gen_random_uuid(), 'PYZINA 750MG TABLET', '', 'Medicines', 77, '', 'ti-pill', '10''S', false, 1),
  (gen_random_uuid(), 'NUCORT M 4MG STRIP OF 10 TABLETS', '', 'Medicines', 59, '', 'ti-pill', '10''S', false, 4),
  (gen_random_uuid(), 'MYCODERM POWDER 150GM 150GM', '', 'Vitamins', 145, '', 'ti-pill', '150GM', false, 1),
  (gen_random_uuid(), 'COLICAID SYRUP 60ML', '', 'Cold & Flu', 159, '', 'ti-bottle', '60 ML', false, 1),
  (gen_random_uuid(), 'CALPOL PAED DROPS 15ML', '', 'Cold & Flu', 31, '', 'ti-bottle', '15ML', false, 3),
  (gen_random_uuid(), 'TUMMY SOFT 5GM BOTTLE OF 50ML DRY SYRUP', '', 'Cold & Flu', 266, '', 'ti-bottle', '50ML', false, 1),
  (gen_random_uuid(), 'TELVAS H 40MG TAB 10`S', '', 'Medicines', 93, '', 'ti-pill', '10`S', false, 1),
  (gen_random_uuid(), 'ZORYL M 1MG STRIP OF 20 TABLETS', '', 'Medicines', 253, '', 'ti-pill', '20''S', false, 1),
  (gen_random_uuid(), 'BETAMIL GM TUBE OF 30GM CREAM', '', 'Skin Care', 54, '', 'ti-spray', '30GM', false, 2),
  (gen_random_uuid(), 'COLIZA D PEPPERMINT FALV SUSP 30ML', '', 'Medicines', 74, '', 'ti-pill', '30ML', false, 1),
  (gen_random_uuid(), 'CANDID TOTAL PLUS CREAM 20 GM', '', 'Skin Care', 116, '', 'ti-spray', '20GM', false, 1),
  (gen_random_uuid(), 'CTD M 6.25/25MG TABLET 10''S', '', 'Medicines', 124, '', 'ti-pill', '10''S', false, 1),
  (gen_random_uuid(), 'ENERZAL ORANGE POW - 75GM', '', 'Vitamins', 53, '', 'ti-pill', '75GM', false, 9),
  (gen_random_uuid(), 'ZEROLAC POWDER 400GM', '', 'Vitamins', 574, '', 'ti-pill', '400GM', false, 7),
  (gen_random_uuid(), 'DIZITAC TABLET 10''S', '', 'Medicines', 141, '', 'ti-pill', '10''S', false, 2),
  (gen_random_uuid(), 'SUPRACAL XT TAB - 15''S', '', 'Medicines', 235, '', 'ti-pill', '15''S', false, 1),
  (gen_random_uuid(), 'RAXNIN SACHET - 5G', '', 'Medicines', 54, '', 'ti-pill', '5G', false, 18),
  (gen_random_uuid(), 'NAPRA D 500MG TAB - 10TAB', '', 'Medicines', 121, '', 'ti-pill', '10TAB', false, 8),
  (gen_random_uuid(), 'EPILIVE 500MG TAB - 15TAB', '', 'Medicines', 208, '', 'ti-pill', '15TAB', false, 6),
  (gen_random_uuid(), 'AACTARIL SOAP 75GM', '', 'Skin Care', 115, '', 'ti-spray', '75GM', false, 1),
  (gen_random_uuid(), 'VOGLINORM GM 1MG STRIP OF 15 TABLETS', '', 'Medicines', 302, '', 'ti-pill', '15''S', false, 2),
  (gen_random_uuid(), 'PREDMET 4MG STRIP OF 15 TABLETS', '', 'Medicines', 90, '', 'ti-pill', '15''S', false, 1),
  (gen_random_uuid(), 'LINARES M STRIP OF 10 TABLETS', '', 'Medicines', 118, '', 'ti-pill', '10''S', false, 3),
  (gen_random_uuid(), 'CARRIAGO GEL - 30GM', '', 'Pain Relief', 187, '', 'ti-pill', '30GM', false, 2),
  (gen_random_uuid(), 'EMOLENE CREAM 100GM 100GM', '', 'Skin Care', 391, '', 'ti-spray', '100GM', false, 1),
  (gen_random_uuid(), 'MACSART H 40/12.5MG TABLET 10''S', '', 'Medicines', 82, '', 'ti-pill', '10''S', false, 4),
  (gen_random_uuid(), 'EVERFLAM SP TAB - 10TAB', '', 'Medicines', 98, '', 'ti-pill', '10TAB', false, 10),
  (gen_random_uuid(), 'UNWANTED 72 TAB - 1''S', '', 'Medicines', 76, '', 'ti-pill', '1''S', false, 2),
  (gen_random_uuid(), 'OMEZ INSTA MINT FLAV SACH 5.9GM 6GM', '', 'Medicines', 18, '', 'ti-pill', '6GM', false, 7),
  (gen_random_uuid(), 'ROZLIV SYP 200ML - 200  ML', '', 'Medicines', 143, '', 'ti-pill', '200  ML', false, 3),
  (gen_random_uuid(), 'R B TONE BOTTLE OF 200ML SYRUP', '', 'Cold & Flu', 225, '', 'ti-bottle', '200ML', false, 1),
  (gen_random_uuid(), 'NASOWASH SACHET 8GM', '', 'Skin Care', 25, '', 'ti-spray', '8GM', false, 10),
  (gen_random_uuid(), 'ORASORE STRIP OF 10 MOUTH ULCER TABLETS', '', 'Medicines', 68, '', 'ti-pill', '10''S', false, 3),
  (gen_random_uuid(), 'ORASORE CHARCOAL TOOTHPASTE - 120GM', '', 'Medicines', 178, '', 'ti-pill', '120GM', false, 1),
  (gen_random_uuid(), 'ELECTRAL POWDER  - 21.8GM', '', 'Vitamins', 23, '', 'ti-pill', '21.8GM', false, 70),
  (gen_random_uuid(), 'MET XL 12.5MG TAB - 20`S', '', 'Medicines', 110, '', 'ti-pill', '20`S', false, 3),
  (gen_random_uuid(), 'ELECTRAL POWDER - 4.4GM', '', 'Vitamins', 5, '', 'ti-pill', '4.4GM', false, 30),
  (gen_random_uuid(), 'DABUR DASHMULARISHTA 450ML', '', 'Medicines', 210, '', 'ti-pill', '450ML', false, 1),
  (gen_random_uuid(), 'ROGAN DIMAGE ROSHAN OIL 400 ML', '', 'Medicines', 285, '', 'ti-pill', '400ML', false, 1),
  (gen_random_uuid(), 'SARTEL 40MG STRIP OF 15 TABLETS', '', 'Medicines', 108, '', 'ti-pill', '15''S', false, 5),
  (gen_random_uuid(), 'AMBROLITE LEVO SYP 100ML', '', 'Medicines', 110, '', 'ti-pill', '100ML', false, 1),
  (gen_random_uuid(), 'SIMYL MCT POWDER 400GM', '', 'Vitamins', 583, '', 'ti-pill', '400GM', false, 5),
  (gen_random_uuid(), 'CARMICIDE DROPS 15ML BOTTLE 15ML', '', 'Cold & Flu', 54, '', 'ti-bottle', '15ML', false, 1),
  (gen_random_uuid(), 'NEERI SYP 200ML', '', 'Medicines', 293, '', 'ti-pill', '200ML', false, 1),
  (gen_random_uuid(), 'OPTIMOIST EYE DROP 10ML', '', 'Cold & Flu', 129, '', 'ti-bottle', '10ML', false, 1),
  (gen_random_uuid(), 'FLUTICONE OX BOTTLE OF 70MD NASAL SPRAY', '', 'Medicines', 392, '', 'ti-pill', '70BOTTLE', false, 1),
  (gen_random_uuid(), 'UPRISE D3 400IU BOTTLE OF 15ML DROPS', '', 'Cold & Flu', 111, '', 'ti-bottle', '15ML', false, 2),
  (gen_random_uuid(), 'CTD O 6.25/40MG TABLET 10''S', '', 'Medicines', 259, '', 'ti-pill', '10''S', false, 1),
  (gen_random_uuid(), 'CITRO SODA SACHET OF 5GM GRANULES', '', 'Medicines', 31, '', 'ti-pill', '5GM', false, 12),
  (gen_random_uuid(), 'ECOSPRIN AV 75MG CAP - 15`S', '', 'Medicines', 61, '', 'ti-pill', '15`S', false, 10),
  (gen_random_uuid(), 'ARISTOZYME SYP 200ML', '', 'Medicines', 152, '', 'ti-pill', '200ML', false, 3),
  (gen_random_uuid(), 'AMLOVAS M 5/50MG TABLET 10''S', '', 'Medicines', 165, '', 'ti-pill', '10''S', false, 1),
  (gen_random_uuid(), 'CONCOR PLUS TABLET 10''S', '', 'Medicines', 185, '', 'ti-pill', '10''S', false, 4),
  (gen_random_uuid(), 'AMLOPIN 5MG STRIP OF 10 TABLETS', '', 'Medicines', 27, '', 'ti-pill', '10`S', false, 1),
  (gen_random_uuid(), 'PIL ELECTROLYTE ORS POW - 21.8GM', '', 'Vitamins', 23, '', 'ti-pill', '21.8GM', false, 60),
  (gen_random_uuid(), 'ISRYL M 1 TAB 15''S', '', 'Medicines', 42, '', 'ti-pill', '15''S', false, 2),
  (gen_random_uuid(), 'FUNGICROS LOTION - 30ML', '', 'Skin Care', 293, '', 'ti-spray', '30ML', false, 1),
  (gen_random_uuid(), 'ROSUMAC GOLD 20MG CAPSULE 10''S', '', 'Medicines', 379, '', 'ti-pill', '10''S', false, 4),
  (gen_random_uuid(), 'HIMALAYA RENALKA SYP 100ML', '', 'Medicines', 112, '', 'ti-pill', '100ML', false, 2),
  (gen_random_uuid(), 'ZEDEX COUGH SYRUP 100 ML', '', 'Cold & Flu', 197, '', 'ti-bottle', '100ML', false, 1),
  (gen_random_uuid(), 'KAYAM TAB 30''S', '', 'Medicines', 117, '', 'ti-pill', '30BOTTLE', false, 1),
  (gen_random_uuid(), 'TEDIBAR SOAP 75GM 75GM', '', 'Skin Care', 209, '', 'ti-spray', '75GM', false, 4),
  (gen_random_uuid(), 'BELLADONA PLASTER MEHTA 0BOX', '', 'First Aid', 19, '', 'ti-medical-cross', '0BOX', false, 50),
  (gen_random_uuid(), 'ISTAVEL 100MG STRIP OF 10 TABLETS', '', 'Medicines', 160, '', 'ti-pill', '10''S', false, 1),
  (gen_random_uuid(), 'FRANXIT TAB 10''S', '', 'Medicines', 95, '', 'ti-pill', '10''S', false, 2),
  (gen_random_uuid(), 'AMLOPRES AT STRIP - 15TAB', '', 'Medicines', 185, '', 'ti-pill', '15TAB', false, 1),
  (gen_random_uuid(), 'RANRAFT SYP - 200ML', '', 'Medicines', 237, '', 'ti-pill', '200ML', false, 1),
  (gen_random_uuid(), 'DEXORANGE SYP 200ML', '', 'Medicines', 197, '', 'ti-pill', '200ML', false, 5),
  (gen_random_uuid(), 'CRINA NCR 15MG TABLET', '', 'Medicines', 129, '', 'ti-pill', '5 NO''S', false, 2),
  (gen_random_uuid(), 'MAGSTONE B6 PINNEAPPLE SF LIQUID 200ML', '', 'Medicines', 239, '', 'ti-pill', '200ML', false, 1),
  (gen_random_uuid(), 'OVACARE MYO STRIP OF 12 TABLETS', '', 'Medicines', 342, '', 'ti-pill', '12''S', false, 3),
  (gen_random_uuid(), 'TRAZER MET TABS - 10TAB', '', 'Medicines', 329, '', 'ti-pill', '10TAB', false, 4),
  (gen_random_uuid(), 'FOSTORIA TABLET 10 NO''S', '', 'Medicines', 196, '', 'ti-pill', '10''S', false, 7),
  (gen_random_uuid(), 'TRIGLYNASE 1MG TABLET 10''S', '', 'Medicines', 64, '', 'ti-pill', '10''S', false, 1),
  (gen_random_uuid(), 'METPURE XL 25MG STRIP OF 10 TABLETS', '', 'Medicines', 152, '', 'ti-pill', '10 NO''S', false, 7),
  (gen_random_uuid(), 'SITARED M 50/500MG STRIP OF 15 TABLETS', '', 'Medicines', 176, '', 'ti-pill', '15''S', false, 2),
  (gen_random_uuid(), 'PANTOCID DSR CAP - 15CAP', '', 'Medicines', 252, '', 'ti-pill', '15CAP', false, 1),
  (gen_random_uuid(), 'SURGICLIN CLINICAL SPIRIT 100ML - 100ML', '', 'Medicines', 48, '', 'ti-pill', '100ML', false, 1),
  (gen_random_uuid(), 'ETHIGLO SOAP 75GM', '', 'Skin Care', 98, '', 'ti-spray', '75GM', false, 1),
  (gen_random_uuid(), 'SULTY TABLET 4 NO''S', '', 'Medicines', 12, '', 'ti-pill', '4''S', false, 20),
  (gen_random_uuid(), 'PUDIN HARA CAPSULE 10 NO''S', '', 'Medicines', 32, '', 'ti-pill', '10''S', false, 6),
  (gen_random_uuid(), 'DABUR PUDIN HARA ACTIVE LIQ 10ML', '', 'Medicines', 28, '', 'ti-pill', '10ML', false, 1),
  (gen_random_uuid(), 'CYSTONE TAB 60``S 60`S', '', 'Medicines', 243, '', 'ti-pill', '60`S', false, 1),
  (gen_random_uuid(), 'TELMA 40MG 30TAB - 30TAB', '', 'Medicines', 213, '', 'ti-pill', '30TAB', false, 3),
  (gen_random_uuid(), 'TETMOSOL SOAP - 100 GRAM', '', 'Skin Care', 96, '', 'ti-spray', '100 GRAM', false, 5),
  (gen_random_uuid(), 'DREAMFERT M TAB - 10TAB', '', 'Medicines', 577, '', 'ti-pill', '10TAB', false, 3),
  (gen_random_uuid(), 'SUTHOL SKIN LOTION - 200ML', '', 'Skin Care', 85, '', 'ti-spray', '200ML', false, 1),
  (gen_random_uuid(), 'SUTHOL ANTISEPTIC LIQUID 100ML', '', 'First Aid', 47, '', 'ti-medical-cross', '100ML', false, 1),
  (gen_random_uuid(), 'SUTHOL CHANDAN LIQUID 100ML', '', 'Medicines', 47, '', 'ti-pill', '100ML', false, 1),
  (gen_random_uuid(), 'DOXINATE FORTE STRIP OF 10 TABLETS', '', 'Medicines', 211, '', 'ti-pill', '10 NO''S', false, 1),
  (gen_random_uuid(), 'GLYCIPHAGE G 1 TABLET 20 NO''S', '', 'Medicines', 96, '', 'ti-pill', '20''S', false, 1),
  (gen_random_uuid(), 'LIBRIUM 10MG STRIP OF 15 TABLETS', '', 'Medicines', 161, '', 'ti-pill', '15 NO''S', false, 1),
  (gen_random_uuid(), 'AMROLSTAR 0.25% W/W CREAM 10GM', '', 'Skin Care', 108, '', 'ti-spray', '10GM', false, 2),
  (gen_random_uuid(), 'TELMIKIND AMH STRIP OF 10 TABLETS', '', 'Medicines', 108, '', 'ti-pill', '10''S', false, 6),
  (gen_random_uuid(), 'ECOSPRIN 75MG STRIP OF 14 TABLETS', '', 'Medicines', 5, '', 'ti-pill', '14 NO''S', false, 10),
  (gen_random_uuid(), 'GLYCOMET GP 1MG TAB - 15`S', '', 'Medicines', 123, '', 'ti-pill', '15`S', false, 12),
  (gen_random_uuid(), 'AMODEP AT STRIP OF 15 TABLETS', '', 'Medicines', 53, '', 'ti-pill', '15''S', false, 3),
  (gen_random_uuid(), 'AARJETRON - 10 TAB - 10TAB', '', 'Medicines', 49, '', 'ti-pill', '10TAB', false, 20),
  (gen_random_uuid(), 'AARJEITRA-200 - 10 CAP - 10CAP', '', 'Medicines', 232, '', 'ti-pill', '10CAP', false, 5),
  (gen_random_uuid(), 'AARJEMOL - SP  - 10TAB', '', 'Medicines', 115, '', 'ti-pill', '10TAB', false, 47),
  (gen_random_uuid(), 'AARJE CLO MR 10 TAB - 10 TAB', '', 'Medicines', 103, '', 'ti-pill', '10 TAB', false, 30),
  (gen_random_uuid(), 'LEMO SYP 60ML', '', 'Medicines', 84, '', 'ti-pill', '60 ML', false, 5),
  (gen_random_uuid(), 'CALAFID SYP -200ML - 200  ML', '', 'Medicines', 110, '', 'ti-pill', '200  ML', false, 2),
  (gen_random_uuid(), 'ADULSA SYP HEALING - 120ML', '', 'Medicines', 84, '', 'ti-pill', '120ML', false, 4),
  (gen_random_uuid(), 'BILAARJE M20 - 10TAB', '', 'Medicines', 154, '', 'ti-pill', '10TAB', false, 4),
  (gen_random_uuid(), 'AARJE FLAM TAB - 10TAB', '', 'Medicines', 112, '', 'ti-pill', '10TAB', false, 20),
  (gen_random_uuid(), 'RATOL GUM TRAP SMALL  - 1UNIT', '', 'Medicines', 50, '', 'ti-pill', '1UNIT', false, 10),
  (gen_random_uuid(), 'LICEL OIL 20ML', '', 'Medicines', 75, '', 'ti-pill', '20ML', false, 4),
  (gen_random_uuid(), '5G VITA PLUS TAB - 10TAB', '', 'Medicines', 185, '', 'ti-pill', '10TAB', false, 2),
  (gen_random_uuid(), 'CANDID B CREAM 20GM 20GM', '', 'Skin Care', 178, '', 'ti-spray', '20GM', false, 2),
  (gen_random_uuid(), 'UNERGY Q10 SOFTGEL CAP - 10C', '', 'Pain Relief', 467, '', 'ti-pill', '10C', false, 6),
  (gen_random_uuid(), 'AVYUZOL DSR CAP - 10 CAP', '', 'Medicines', 103, '', 'ti-pill', '10 CAP', false, 2),
  (gen_random_uuid(), 'MYOSTAAL LINIMENT 30ML', '', 'Medicines', 98, '', 'ti-pill', '30ML', false, 2),
  (gen_random_uuid(), 'THROMBOPHOB OINT  - 20GM', '', 'Medicines', 237, '', 'ti-pill', '20GM', false, 1),
  (gen_random_uuid(), 'TIMOLET OD EYE DROPS 3ML', '', 'Cold & Flu', 43, '', 'ti-bottle', '3ML', false, 2),
  (gen_random_uuid(), 'FORACORT 400MCG ROTACAPS 30''S', '', 'Medicines', 223, '', 'ti-pill', '30BOX', false, 1),
  (gen_random_uuid(), 'OXIRAY SYP 200ML', '', 'Medicines', 159, '', 'ti-pill', '200ML', false, 2),
  (gen_random_uuid(), 'CIPLADINE SOLU 100ML', '', 'Medicines', 46, '', 'ti-pill', '100ML', false, 1),
  (gen_random_uuid(), 'PAN D CAP - 15CAP', '', 'Medicines', 238, '', 'ti-pill', '15CAP', false, 2),
  (gen_random_uuid(), 'XILINGIO M 10/5/1000 - 10S', '', 'Medicines', 173, '', 'ti-pill', '10S', false, 4),
  (gen_random_uuid(), 'COCOMMINE POWDER - 10GM', '', 'Vitamins', 79, '', 'ti-pill', '10GM', false, 4),
  (gen_random_uuid(), 'BRONKOLYTE LS SYP - 100ML', '', 'Medicines', 135, '', 'ti-pill', '100ML', false, 2),
  (gen_random_uuid(), 'RINIFOL Z DRY SYP 60ML', '', 'Medicines', 117, '', 'ti-pill', '60ML', false, 3),
  (gen_random_uuid(), 'I KUL BOTTLE OF 10ML EYE DROPS', '', 'Cold & Flu', 80, '', 'ti-bottle', '10 ML', false, 2),
  (gen_random_uuid(), 'VORKING STRIP OF 10 CAPSULES', '', 'Medicines', 141, '', 'ti-pill', '10 NO''S', false, 10),
  (gen_random_uuid(), 'EXAMINATION GLOVES (M) NITRILE 1''S', '', 'Medicines', 928, '', 'ti-pill', '1PACKET', false, 1),
  (gen_random_uuid(), 'SOLEARWAX EAR DROPS 10ML', '', 'Cold & Flu', 75, '', 'ti-bottle', '10ML', false, 3),
  (gen_random_uuid(), 'TELNIGLIP 20MG STRIP OF 10 TABLETS', '', 'Medicines', 117, '', 'ti-pill', '10''S', false, 3),
  (gen_random_uuid(), 'CALCITEROLIN 0.25  CALCITRIOL  - 10CAP', '', 'Medicines', 93, '', 'ti-pill', '10CAP', false, 12),
  (gen_random_uuid(), 'GLIMP MP 1MG TAB - 10''S', '', 'Medicines', 146, '', 'ti-pill', '10''S', false, 3),
  (gen_random_uuid(), 'X-HEAL FACE WASH - 60 ML', '', 'Skin Care', 150, '', 'ti-spray', '60 ML', false, 2),
  (gen_random_uuid(), 'RINIFOL DRY SYP 60ML', '', 'Medicines', 80, '', 'ti-pill', '60ML', false, 3),
  (gen_random_uuid(), 'TRYPTOMER 10MG TAB 30`S', '', 'Medicines', 76, '', 'ti-pill', '30`S', false, 3),
  (gen_random_uuid(), 'CLOPITAB A 75 CAP - 15S', '', 'Medicines', 138, '', 'ti-pill', '15S', false, 3),
  (gen_random_uuid(), 'MCROTEL 40MG TAB 10''S', '', 'Medicines', 63, '', 'ti-pill', '10 NO''S', false, 2),
  (gen_random_uuid(), 'JUNIOR LANZOL 15MG STRIP OF 15 TABLETS', '', 'Medicines', 185, '', 'ti-pill', '15''S', false, 1),
  (gen_random_uuid(), 'GEMER 2MG STRIP OF 15 TABLETS', '', 'Medicines', 237, '', 'ti-pill', '15''S', false, 4),
  (gen_random_uuid(), 'ERITEL CH 40MG STRIP OF 15 TABLETS', '', 'Medicines', 262, '', 'ti-pill', '15''S', false, 3),
  (gen_random_uuid(), 'VILPOWER DM 500 TAB - 10TAB', '', 'Medicines', 169, '', 'ti-pill', '10TAB', false, 5),
  (gen_random_uuid(), 'ONDEM SYP - 30ML', '', 'Medicines', 40, '', 'ti-pill', '30ML', false, 9),
  (gen_random_uuid(), 'SODAMINT TAB 100''S', '', 'Medicines', 55, '', 'ti-pill', '100BOTTLE', false, 1),
  (gen_random_uuid(), 'MONISON''S BALM - 10GM', '', 'Pain Relief', 34, '', 'ti-pill', '10GM', false, 3),
  (gen_random_uuid(), 'MONISON''S BALM 25GM', '', 'Pain Relief', 68, '', 'ti-pill', '25GM', false, 3),
  (gen_random_uuid(), 'ERANDEL TEL OIL 200ML', '', 'Medicines', 72, '', 'ti-pill', '200ML', false, 8),
  (gen_random_uuid(), 'ULTRA Q 300MG STRIP OF 15 CAPSULES', '', 'Medicines', 1500, '', 'ti-pill', '15''S', false, 2),
  (gen_random_uuid(), 'SEBAMED BABY CREAM EXTRA SOFT - 50ML', '', 'Skin Care', 270, '', 'ti-spray', '50ML', false, 1),
  (gen_random_uuid(), 'BABYFIVE DROP - 5ML', '', 'Cold & Flu', 605, '', 'ti-bottle', '5ML', false, 1),
  (gen_random_uuid(), 'CYCLOSET BOTTLE OF 300ML SYRUP', '', 'Cold & Flu', 326, '', 'ti-bottle', '300ML', false, 1),
  (gen_random_uuid(), 'INSTAFLEX GEL 30GM', '', 'Pain Relief', 206, '', 'ti-pill', '30GM', false, 1),
  (gen_random_uuid(), 'FOLVITE TAB 45`S', '', 'Medicines', 73, '', 'ti-pill', '45`S', false, 2),
  (gen_random_uuid(), 'CANDID 1% LOTION 30ML', '', 'Skin Care', 125, '', 'ti-spray', '30 ML', false, 1),
  (gen_random_uuid(), 'THERMOSEAL PROXA BRUSH 1PACKET', '', 'Medicines', 165, '', 'ti-pill', '1PACKET', false, 1),
  (gen_random_uuid(), 'PROHANCE CHOCOLATE NUTRITION DRINK TIN OF 400 G', '', 'Medicines', 632, '', 'ti-pill', '400GM', false, 1),
  (gen_random_uuid(), 'THYRONORM 100MCG TAB 120``S 120`S', '', 'Medicines', 169, '', 'ti-pill', '120`S', false, 2),
  (gen_random_uuid(), 'HAWABAN HARDE JAR 10/- - 5GM', '', 'Medicines', 150, '', 'ti-pill', '5GM', false, 1),
  (gen_random_uuid(), 'JALJEERA   HAWABAN  - 3GMX50', '', 'Medicines', 47, '', 'ti-pill', '3GMX50', false, 3),
  (gen_random_uuid(), 'FASTAC STRIP OF 15 TABLETS', '', 'Medicines', 59, '', 'ti-pill', '15''S', false, 4),
  (gen_random_uuid(), 'CUREON PLUS OIL - 100ML', '', 'Medicines', 206, '', 'ti-pill', '100ML', false, 1),
  (gen_random_uuid(), 'ZINCOVIT TAB - 15TAB', '', 'Medicines', 108, '', 'ti-pill', '15TAB', false, 1),
  (gen_random_uuid(), 'ZERODOL SP TABLET', '', 'Medicines', 140, '', 'ti-pill', '10 STRIP', false, 5),
  (gen_random_uuid(), 'CUTIMAX O TUBE OF 200GM LOTION', '', 'Skin Care', 722, '', 'ti-spray', '200GM', false, 1),
  (gen_random_uuid(), 'EMBETA XR 50MG STRIP OF 30 TABLETS', '', 'Medicines', 187, '', 'ti-pill', '30 NO''S', false, 1),
  (gen_random_uuid(), 'CTD O 6.25/40MG TAB 15''S', '', 'Medicines', 276, '', 'ti-pill', '15''S', false, 1),
  (gen_random_uuid(), 'CIPLOX E/E DROPS 10ML 10ML', '', 'Cold & Flu', 16, '', 'ti-bottle', '10ML', false, 5),
  (gen_random_uuid(), 'TAXIM O BOTTLE OF 30ML DRY SYRUP', '', 'Cold & Flu', 52, '', 'ti-bottle', '30ML', false, 1),
  (gen_random_uuid(), 'OBIMET GX 1MG STRIP OF 15 TABLETS', '', 'Medicines', 202, '', 'ti-pill', '15''S', false, 2),
  (gen_random_uuid(), 'MONTICOPE STRIP OF 10 TABLETS', '', 'Medicines', 103, '', 'ti-pill', '10''S', false, 2),
  (gen_random_uuid(), 'GLYCOMET GP 3 850MG TAB - 15TAB', '', 'Medicines', 168, '', 'ti-pill', '15TAB', false, 3),
  (gen_random_uuid(), 'ROSUFIT 10MG', '', 'Medicines', 268, '', 'ti-pill', '10''S', false, 1),
  (gen_random_uuid(), 'GLURA MP 500 - 10 TAB', '', 'Medicines', 192, '', 'ti-pill', '10 TAB', false, 5),
  (gen_random_uuid(), 'NOSTRA CR 15MG TAB 5''S', '', 'Medicines', 148, '', 'ti-pill', '5''S', false, 1),
  (gen_random_uuid(), 'GLYCOMET GP 0.5 15TAB  - 15 TAB', '', 'Medicines', 89, '', 'ti-pill', '15 TAB', false, 4),
  (gen_random_uuid(), 'GLYREE MV 1MG TABLET 10''S', '', 'Medicines', 175, '', 'ti-pill', '10''S', false, 3),
  (gen_random_uuid(), 'PERINORM 10MG TABLET', '', 'Medicines', 14, '', 'ti-pill', '10''S', false, 2),
  (gen_random_uuid(), 'CLINDAC A GEL 20GM 20GM', '', 'Pain Relief', 252, '', 'ti-pill', '20GM', false, 1),
  (gen_random_uuid(), 'CRINA NCR 10MG TAB 10``S 10`S', '', 'Medicines', 212, '', 'ti-pill', '10`S', false, 1),
  (gen_random_uuid(), 'BILAZAP M STRIP OF 10 TABLETS', '', 'Medicines', 187, '', 'ti-pill', '10''S', false, 1),
  (gen_random_uuid(), 'ZERODOL P TABLET 10''S', '', 'Medicines', 76, '', 'ti-pill', '10''S', false, 2),
  (gen_random_uuid(), 'KDCALCIUM  TAB - 10 TAB', '', 'Vitamins', 158, '', 'ti-pill', '10 TAB', false, 2),
  (gen_random_uuid(), 'NACHANI SATWA BADAM JIN - 250GM', '', 'Medicines', 100, '', 'ti-pill', '250GM', false, 4),
  (gen_random_uuid(), 'MULTANI MATTI BOX - 50GM', '', 'Medicines', 35, '', 'ti-pill', '50GM', false, 4),
  (gen_random_uuid(), 'KAYAM CHURNA 50GM', '', 'Medicines', 59, '', 'ti-pill', '50GM', false, 3),
  (gen_random_uuid(), 'MENTHODEX PAIN BALM - 10GM', '', 'Pain Relief', 25, '', 'ti-pill', '10GM', false, 4),
  (gen_random_uuid(), 'PLATIGEN CAP - 10 CAP', '', 'Medicines', 328, '', 'ti-pill', '10 CAP', false, 3),
  (gen_random_uuid(), 'DAPATRUST-M 10/500 - 15TAB', '', 'Medicines', 143, '', 'ti-pill', '15TAB', false, 7),
  (gen_random_uuid(), 'CHYMOTAS FORTE TABLET 20''S', '', 'Medicines', 486, '', 'ti-pill', '20''S', false, 3),
  (gen_random_uuid(), 'ALKEMZYME DIGESTIVE TAB - 15TAB', '', 'Medicines', 98, '', 'ti-pill', '15TAB', false, 2),
  (gen_random_uuid(), 'PHYSITEL TRIO 6.25 MG TAB - 10TAB', '', 'Medicines', 103, '', 'ti-pill', '10TAB', false, 2),
  (gen_random_uuid(), 'BYZEPTA  -10TAB - 10TAB', '', 'Medicines', 1067, '', 'ti-pill', '10TAB', false, 1),
  (gen_random_uuid(), 'CLASSMET G 1MG STRIP OF 15 TABLETS', '', 'Medicines', 113, '', 'ti-pill', '15''S', false, 2),
  (gen_random_uuid(), 'SAPAT BOTTLE OF 25ML LOTION', '', 'Skin Care', 70, '', 'ti-spray', '25ML', false, 6),
  (gen_random_uuid(), 'KHATNIL SPRAY - 500ML', '', 'Medicines', 280, '', 'ti-pill', '500ML', false, 5),
  (gen_random_uuid(), 'ZEMPRED 4MG TAB 10`S', '', 'Medicines', 60, '', 'ti-pill', '10`S', false, 4),
  (gen_random_uuid(), 'ZANOCIN 50MG ORAL SOLUTION 60ML', '', 'Medicines', 83, '', 'ti-pill', '60ML', false, 3),
  (gen_random_uuid(), 'ZANOCIN 200MG TAB - 10 NO''S', '', 'Medicines', 102, '', 'ti-pill', '10 NO''S', false, 5),
  (gen_random_uuid(), 'VYLDA M 500MG TABLET 10''S', '', 'Medicines', 180, '', 'ti-pill', '10''S', false, 2),
  (gen_random_uuid(), 'MEFTAL P SUSP 60ML', '', 'Medicines', 35, '', 'ti-pill', '60ML', false, 5),
  (gen_random_uuid(), 'VOGLIGRESS 0.3MG STRIP OF 10 TABLETS', '', 'Medicines', 137, '', 'ti-pill', '10''S', false, 8),
  (gen_random_uuid(), 'PIOZ 7.5MG STRIP OF 10 TABLETS', '', 'Medicines', 106, '', 'ti-pill', '10''S', false, 9),
  (gen_random_uuid(), 'ASTHALIN 200MCG BOX OF 60 ROTACAPS', '', 'Medicines', 65, '', 'ti-pill', '60BOX', false, 3),
  (gen_random_uuid(), 'BILAMBIC M STRIP OF 10 TABLETS', '', 'Medicines', 133, '', 'ti-pill', '10''S', false, 1),
  (gen_random_uuid(), 'ASCORIL LS JUNIOR BOTTLE OF 60ML EXPECTORANT BOTTLE 60ML', '', 'Medicines', 109, '', 'ti-pill', '60ML', false, 2),
  (gen_random_uuid(), 'ALEX COUGH FORMULA SYP 100ML 100ML', '', 'Cold & Flu', 158, '', 'ti-bottle', '100ML', false, 1),
  (gen_random_uuid(), 'CINNAMON CAP 60''S', '', 'Medicines', 180, '', 'ti-pill', '60''S', false, 1),
  (gen_random_uuid(), 'PILON TAB 10''S', '', 'Medicines', 49, '', 'ti-pill', '10''S', false, 1),
  (gen_random_uuid(), 'STAMLO D TAB  - 15TAB', '', 'Medicines', 161, '', 'ti-pill', '15TAB', false, 2),
  (gen_random_uuid(), 'AMANZA MV 2 TABLET 10 NO''S', '', 'Medicines', 143, '', 'ti-pill', '10''S', false, 9),
  (gen_random_uuid(), 'AMBOLEV 5MG TABLET STRIP 10 NO''S', '', 'Medicines', 32, '', 'ti-pill', '10 NO''S', false, 13),
  (gen_random_uuid(), 'PETALIFE DXR CAPSULE 10''S', '', 'Medicines', 129, '', 'ti-pill', '10''S', false, 2),
  (gen_random_uuid(), 'MEDILAX SYP 100ML', '', 'Medicines', 103, '', 'ti-pill', '100ML', false, 3),
  (gen_random_uuid(), 'TRIPHALA CHURNA 50GM', '', 'Medicines', 55, '', 'ti-pill', '50GM', false, 1),
  (gen_random_uuid(), 'TRIPHALA CHURNA 60GM', '', 'Medicines', 45, '', 'ti-pill', '60GM', false, 1),
  (gen_random_uuid(), 'ENERZAL ZERO ORANGE FLAVOUR 5G POWDER', '', 'Vitamins', 17, '', 'ti-pill', '5GM', false, 7),
  (gen_random_uuid(), 'DUPHALAC BOTTLE OF 450ML SOLUTION', '', 'Medicines', 591, '', 'ti-pill', '450 ML', false, 1),
  (gen_random_uuid(), 'WARF 5MG TAB - 30TAB', '', 'Medicines', 77, '', 'ti-pill', '30TAB', false, 2),
  (gen_random_uuid(), 'ROSUMAC ASP 10/75MG CAP 10`S', '', 'Medicines', 91, '', 'ti-pill', '10`S', false, 1),
  (gen_random_uuid(), 'AZTOR 10MG STRIP OF 15 TABLETS', '', 'Medicines', 80, '', 'ti-pill', '15''S', false, 5),
  (gen_random_uuid(), 'FERODEN-XT -  10TAB - 10 TAB', '', 'Medicines', 112, '', 'ti-pill', '10 TAB', false, 1),
  (gen_random_uuid(), 'CETAPHIL GENTLE SENSITIVE SKIN CLEANSER 125ML LOTION 125ML', '', 'Skin Care', 429, '', 'ti-spray', '125ML', false, 1),
  (gen_random_uuid(), 'ULTRAMAX TAB - 15TAB', '', 'Medicines', 169, '', 'ti-pill', '15TAB', false, 4),
  (gen_random_uuid(), 'PREGAFAB NT TAB - 10 TAB', '', 'Medicines', 131, '', 'ti-pill', '10 TAB', false, 5),
  (gen_random_uuid(), 'OTRIVIN OXY ADULT NASAL DROP 10ML', '', 'Cold & Flu', 121, '', 'ti-bottle', '10ML', false, 2),
  (gen_random_uuid(), 'NEO MERCAZOLE 10MG TABLET 120''S', '', 'Medicines', 591, '', 'ti-pill', '120 NO''S', false, 2),
  (gen_random_uuid(), 'ODIMONT FX TABLET 15''S', '', 'Medicines', 323, '', 'ti-pill', '15''S', false, 1),
  (gen_random_uuid(), 'THYRONORM 150MCG BOTTLE OF 120 TABLETS', '', 'Medicines', 218, '', 'ti-pill', '120BOTTLE', false, 1),
  (gen_random_uuid(), 'PENTIDS 400  - 10tab', '', 'Stationery', 25, '', 'ti-pill', '10TAB', false, 6),
  (gen_random_uuid(), 'HENZOVIT CAP 10`S', '', 'Medicines', 168, '', 'ti-pill', '10`S', false, 3),
  (gen_random_uuid(), 'LACTIFIBER GRANULES 180GM PCS 1X1', '', 'Medicines', 516, '', 'ti-pill', '1X1', false, 1),
  (gen_random_uuid(), 'GLIMY SM1 FORTE TABS - 10TAB', '', 'Medicines', 154, '', 'ti-pill', '10TAB', false, 2),
  (gen_random_uuid(), 'LEVIPIL SYP 100ML', '', 'Medicines', 424, '', 'ti-pill', '100ML', false, 2),
  (gen_random_uuid(), 'BUDECORT 0.5MG RESPULES 2ML', '', 'Medicines', 25, '', 'ti-pill', '2ML', false, 60),
  (gen_random_uuid(), 'DYDROBOON STRIP OF 10 TABLETS', '', 'Medicines', 668, '', 'ti-pill', '10''S', false, 4),
  (gen_random_uuid(), 'ROSUVAS 10MG STRIP OF 15 TABLETS', '', 'Medicines', 346, '', 'ti-pill', '15''S', false, 1),
  (gen_random_uuid(), 'SHELCAL 500MG TAB - 15`S', '', 'Medicines', 163, '', 'ti-pill', '15`S', false, 2),
  (gen_random_uuid(), 'MACSART AM 40MG STRIP OF 10 TABLETS', '', 'Medicines', 76, '', 'ti-pill', '10''S', false, 2),
  (gen_random_uuid(), 'PAN 40MG TAB 15`S', '', 'Medicines', 193, '', 'ti-pill', '15`S', false, 2),
  (gen_random_uuid(), 'DUOLIN 3 RESPULES 3ML 3ML', '', 'Medicines', 26, '', 'ti-pill', '3ML', false, 111),
  (gen_random_uuid(), 'LIV 52 TAB - 100 NO''S', '', 'Medicines', 220, '', 'ti-pill', '100 NO''S', false, 1),
  (gen_random_uuid(), 'FORACORT 200MCG ROTACAPS', '', 'Medicines', 183, '', 'ti-pill', '30 NO''S', false, 1),
  (gen_random_uuid(), 'CREMAFFIN PLUS SYP 225ML - 225ML', '', 'Medicines', 338, '', 'ti-pill', '225ML', false, 4),
  (gen_random_uuid(), 'YESAKA SYRUP 600ML', '', 'Cold & Flu', 288, '', 'ti-bottle', '600ML', false, 2),
  (gen_random_uuid(), 'AMRUTANJAN PAIN RELIEF BALM BOTTLE OF 50 ML', '', 'Pain Relief', 141, '', 'ti-pill', '50ML', false, 1),
  (gen_random_uuid(), 'ISRYL M 2MG TAB 15''S', '', 'Medicines', 63, '', 'ti-pill', '15''S', false, 9),
  (gen_random_uuid(), 'DUPHALAC SOLUTION 150ML - 150ML', '', 'Medicines', 197, '', 'ti-pill', '150ML', false, 1),
  (gen_random_uuid(), 'WARF 5MG TABLET 30''S', '', 'Medicines', 77, '', 'ti-pill', '30''S', false, 1),
  (gen_random_uuid(), 'PROLOMET XL 25MG TAB - 15TAB', '', 'Medicines', 68, '', 'ti-pill', '15TAB', false, 2),
  (gen_random_uuid(), 'LASILACTONE 50MG TAB 10`S', '', 'Medicines', 67, '', 'ti-pill', '10`S', false, 3),
  (gen_random_uuid(), 'DILZEM 30MG 15''S', '', 'Medicines', 43, '', 'ti-pill', '15''S', false, 3),
  (gen_random_uuid(), 'K GLIM M1 TAB 15''S', '', 'Medicines', 61, '', 'ti-pill', '15''S', false, 4),
  (gen_random_uuid(), 'AB PHYLLINE 15CAP - 15CAP', '', 'Medicines', 300, '', 'ti-pill', '15CAP', false, 2),
  (gen_random_uuid(), 'MICOB SUGAR FREE SYRUP 150 ML', '', 'Cold & Flu', 488, '', 'ti-bottle', '150ML', false, 2),
  (gen_random_uuid(), 'CYRA D CAP 10`S 10`S', '', 'Medicines', 48, '', 'ti-pill', '10`S', false, 2),
  (gen_random_uuid(), 'LUKOTAS HD STRIP OF 10 TABLETS', '', 'Medicines', 220, '', 'ti-pill', '10''S', false, 4),
  (gen_random_uuid(), 'NEUROBION FORTE TAB - 30 NO''S', '', 'Medicines', 48, '', 'ti-pill', '30 NO''S', false, 9),
  (gen_random_uuid(), 'ATARAX DROPS 15ML', '', 'Cold & Flu', 86, '', 'ti-bottle', '15ML', false, 4),
  (gen_random_uuid(), 'RA THERMOSEAL FRESH MINT TOOTHPASTE 50GM', '', 'Medicines', 82, '', 'ti-pill', '50GM', false, 3),
  (gen_random_uuid(), 'THERMOSEAL RA PASTE 100GM', '', 'Medicines', 159, '', 'ti-pill', '100 G', false, 3),
  (gen_random_uuid(), 'TONOFERON DROPS 15ML', '', 'Cold & Flu', 108, '', 'ti-bottle', '15ML', false, 1),
  (gen_random_uuid(), 'GECOMOL GEL -30GM - 30GM', '', 'Pain Relief', 103, '', 'ti-pill', '30GM', false, 5),
  (gen_random_uuid(), 'FAMLYVIT - 15 TAB - 15TAB', '', 'Medicines', 141, '', 'ti-pill', '15TAB', false, 4),
  (gen_random_uuid(), 'CANDEAS DUSTING POWDER-100GM - 100GM', '', 'Vitamins', 107, '', 'ti-pill', '100GM', false, 10),
  (gen_random_uuid(), 'FEMINA XT TABLET 10''S', '', 'Medicines', 190, '', 'ti-pill', '10''S', false, 5),
  (gen_random_uuid(), 'COR 3 TAB - 15''S', '', 'Medicines', 299, '', 'ti-pill', '15''S', false, 3),
  (gen_random_uuid(), 'ABHAYRAB INJ 0.5ML 1ML', '', 'Medicines', 405, '', 'ti-pill', '1ML', false, 3),
  (gen_random_uuid(), 'HIMALAYA SHISHU ANAND BABY WIPE 72 NO''S', '', 'Medicines', 99, '', 'ti-pill', '72PACKET', false, 4),
  (gen_random_uuid(), 'WIKORYL SUSP - 60 ML', '', 'Medicines', 117, '', 'ti-pill', '60 ML', false, 1),
  (gen_random_uuid(), 'POLYBION LC MANGO FLAVOUR BOTTLE OF 150ML SYRUP', '', 'Cold & Flu', 142, '', 'ti-bottle', '150ML', false, 1),
  (gen_random_uuid(), 'WIKORYL DS SUSP - 60 ML', '', 'Medicines', 103, '', 'ti-pill', '60 ML', false, 1),
  (gen_random_uuid(), 'TUSQ X BOTTLE OF 100ML EXPECTORANT', '', 'Medicines', 103, '', 'ti-pill', '100ML', false, 2),
  (gen_random_uuid(), 'TELTEL AM TAB - 15TAB', '', 'Medicines', 116, '', 'ti-pill', '15TAB', false, 2),
  (gen_random_uuid(), 'PIONORM 15MG TABLET 10''S', '', 'Medicines', 82, '', 'ti-pill', '10''S', false, 4),
  (gen_random_uuid(), 'DOXOLIN 400MG STRIP OF 30 TABLETS', '', 'Medicines', 144, '', 'ti-pill', '30 NO''S', false, 2),
  (gen_random_uuid(), 'BRENTAMIN STRIP OF 10 TABLETS', '', 'Medicines', 239, '', 'ti-pill', '10''S', false, 3),
  (gen_random_uuid(), 'CIPLOX 500MG TABLET', '', 'Medicines', 45, '', 'ti-pill', '10`S', false, 3),
  (gen_random_uuid(), 'SITAMAX GM 2 FORTE TABS - 10TAB', '', 'Medicines', 143, '', 'ti-pill', '10TAB', false, 2),
  (gen_random_uuid(), 'VOGLIGRESS 0.2MG STRIP OF 10 TABLETS', '', 'Medicines', 106, '', 'ti-pill', '10''S', false, 1),
  (gen_random_uuid(), 'RENOPRESS XL 5MG 10''S', '', 'Medicines', 130, '', 'ti-pill', '10''S', false, 2),
  (gen_random_uuid(), 'NUTROLIN B BOTTLE OF 60ML SYRUP', '', 'Cold & Flu', 69, '', 'ti-bottle', '60ML', false, 1),
  (gen_random_uuid(), 'ISTAMET 50/500MG TAB 15`S', '', 'Medicines', 176, '', 'ti-pill', '15`S', false, 2),
  (gen_random_uuid(), 'GIBTULIO 25MG STRIP OF 10 TABLETS', '', 'Medicines', 159, '', 'ti-pill', '10 NO''S', false, 3),
  (gen_random_uuid(), 'SPORLAC EVA CAPS - 10CAP', '', 'Medicines', 561, '', 'ti-pill', '10CAP', false, 6),
  (gen_random_uuid(), 'IGCAID SYP - 60ML', '', 'Medicines', 89, '', 'ti-pill', '60ML', false, 1),
  (gen_random_uuid(), 'ZONEGRAN 100MG STRIP OF 10 TABLETS', '', 'Medicines', 269, '', 'ti-pill', '10''S', false, 3),
  (gen_random_uuid(), 'WALAMYCIN SUSP 30ML 30ML', '', 'Medicines', 71, '', 'ti-pill', '30ML', false, 2),
  (gen_random_uuid(), 'GLIMIP 0.5MG TAB - 10TAB', '', 'Medicines', 46, '', 'ti-pill', '10TAB', false, 9),
  (gen_random_uuid(), 'ZEFWAY 200MG DT STRIP OF 10 TABLETS', '', 'Medicines', 104, '', 'ti-pill', '10''S', false, 3),
  (gen_random_uuid(), 'DICLOGEM TABLET', '', 'Medicines', 28, '', 'ti-pill', '100 STRIP', false, 20),
  (gen_random_uuid(), 'CEFLOX D E/E DROPS 10ML', '', 'Cold & Flu', 69, '', 'ti-bottle', '100 MILLILITRE', false, 4),
  (gen_random_uuid(), 'KUFTIVE TAB 10''S', '', 'Medicines', 28, '', 'ti-pill', '10''S', false, 0),
  (gen_random_uuid(), 'METNI 8MG STRIP OF 10 TABLETS', '', 'Medicines', 65, '', 'ti-pill', '10''S', false, 2),
  (gen_random_uuid(), 'ROSUVASTIN GOLD 20MG STRIP OF 10 CAPSULES', '', 'Medicines', 258, '', 'ti-pill', '10''S', false, 3),
  (gen_random_uuid(), 'PROTEEN PLUS POW - 200 GM', '', 'Medicines', 511, '', 'ti-pill', '200 GM', false, 5),
  (gen_random_uuid(), 'REXCOF DX NF BOTTLE OF 100ML SYRUP', '', 'Cold & Flu', 145, '', 'ti-bottle', '100ML', false, 3),
  (gen_random_uuid(), 'EVERFRESH 0.5% TEARS EYE DROP 10ML', '', 'Cold & Flu', 131, '', 'ti-bottle', '10ML', false, 3),
  (gen_random_uuid(), 'NAYLAX TAB - 30TAB', '', 'Medicines', 160, '', 'ti-pill', '30TAB', false, 2),
  (gen_random_uuid(), 'LEFNO 10MG TABLET', '', 'Medicines', 155, '', 'ti-pill', '10 NO''S', false, 2),
  (gen_random_uuid(), 'HCQS 300MG TABLET', '', 'Medicines', 346, '', 'ti-pill', '10 NO''S', false, 2),
  (gen_random_uuid(), 'THYRONORM 25MCG TAB 120``S 120`S', '', 'Medicines', 185, '', 'ti-pill', '120`S', false, 2),
  (gen_random_uuid(), 'PANDERM PLUS CREAM 15GM', '', 'Skin Care', 110, '', 'ti-spray', '15GM', false, 4),
  (gen_random_uuid(), 'NUTROLIN B PLUS - 15CAP', '', 'Medicines', 63, '', 'ti-pill', '15CAP', false, 4),
  (gen_random_uuid(), 'DAPANORM L 10MG TAB - 10TAB', '', 'Medicines', 187, '', 'ti-pill', '10TAB', false, 3),
  (gen_random_uuid(), 'CANDID V3 TAB 3`S', '', 'Medicines', 87, '', 'ti-pill', '3`S', false, 1),
  (gen_random_uuid(), 'AMLOKIND 5MG STRIP OF 15 TABLETS', '', 'Medicines', 61, '', 'ti-pill', '15''S', false, 2),
  (gen_random_uuid(), 'CLEAR 1% GEL 20 GM', '', 'Pain Relief', 183, '', 'ti-pill', '20 G', false, 1),
  (gen_random_uuid(), 'MITOCAL CCM STRIP OF 15 TABLETS', '', 'Medicines', 105, '', 'ti-pill', '15''S', false, 3),
  (gen_random_uuid(), 'TEL TEL AM STRIP OF 10 TABLETS', '', 'Medicines', 116, '', 'ti-pill', '10''S', false, 1),
  (gen_random_uuid(), 'ARNOPEN LINIMENT 60ML', '', 'Stationery', 145, '', 'ti-pill', '60ML', false, 1),
  (gen_random_uuid(), 'SEEMOL TOOTH POWDER - NOS', '', 'Vitamins', 30, '', 'ti-pill', 'NOS', false, 1),
  (gen_random_uuid(), 'NAPROPASS 250 TAB - 15TAB', '', 'Medicines', 113, '', 'ti-pill', '15TAB', false, 3),
  (gen_random_uuid(), 'GLYCOMET TRIO 2MG TABLET 10''S', '', 'Medicines', 212, '', 'ti-pill', '10''S', false, 5),
  (gen_random_uuid(), 'AMLONG TRIO 40/5/12.5MG - 10 TAB - 10 TAB', '', 'Medicines', 173, '', 'ti-pill', '10 TAB', false, 4),
  (gen_random_uuid(), 'SKINRISE MOIST LOTION - 100ML', '', 'Skin Care', 200, '', 'ti-spray', '100ML', false, 1),
  (gen_random_uuid(), 'SARPOT 50MG TABLET 10''S', '', 'Medicines', 56, '', 'ti-pill', '10''S', false, 1),
  (gen_random_uuid(), 'OILATUM 7.5% BAR 100GM', '', 'Medicines', 238, '', 'ti-pill', '100GM', false, 1),
  (gen_random_uuid(), 'TELMA AM TAB - 15TAB', '', 'Medicines', 342, '', 'ti-pill', '15TAB', false, 4),
  (gen_random_uuid(), 'TELVAS H 40/12.5MG TABLET 10''S', '', 'Medicines', 93, '', 'ti-pill', '10''S', false, 1),
  (gen_random_uuid(), 'FOLVITE DHA CAP 10''S', '', 'Medicines', 249, '', 'ti-pill', '10''S', false, 2),
  (gen_random_uuid(), 'CLEAN AND DRY DAILY INTIMATE POWDER 100GM', '', 'Vitamins', 164, '', 'ti-pill', '100GM', false, 1),
  (gen_random_uuid(), 'ZOLAX SR 0.5MG TAB 10''S', '', 'Medicines', 58, '', 'ti-pill', '10''S', false, 2),
  (gen_random_uuid(), 'NUCOXIA 90MG TAB 15''S', '', 'Medicines', 318, '', 'ti-pill', '15 NO''S', false, 2),
  (gen_random_uuid(), 'MEFTAL SPAS TABLET', '', 'Medicines', 52, '', 'ti-pill', '10 NO''S', false, 4),
  (gen_random_uuid(), 'LITHOSUN SR 400MG STRIP OF 10 TABLETS', '', 'Medicines', 84, '', 'ti-pill', '10''S', false, 8),
  (gen_random_uuid(), 'CLOBA 5MG TAB 15''S', '', 'Medicines', 92, '', 'ti-pill', '15''S', false, 3),
  (gen_random_uuid(), 'TESS PASTE 5GM', '', 'Medicines', 153, '', 'ti-pill', '5 G', false, 2),
  (gen_random_uuid(), 'O2M DELICIOUS MANGO FLAV SUSP 60ML', '', 'Medicines', 86, '', 'ti-pill', '60ML', false, 1),
  (gen_random_uuid(), 'O2 SUSPENSION 60ML BOTTLE 60ML', '', 'Stationery', 86, '', 'ti-pill', '60ML', false, 1),
  (gen_random_uuid(), 'MUCOLITE SYP 100ML 100ML', '', 'Medicines', 141, '', 'ti-pill', '100ML', false, 1),
  (gen_random_uuid(), 'MAXTRA SYP 60ML', '', 'Medicines', 116, '', 'ti-pill', '60ML', false, 2),
  (gen_random_uuid(), 'DIAMOX 250MG TABLET 10''S', '', 'Medicines', 65, '', 'ti-pill', '10''S', false, 1),
  (gen_random_uuid(), 'CODISTAR DX SYP - 100ML', '', 'Medicines', 103, '', 'ti-pill', '100ML', false, 1),
  (gen_random_uuid(), 'VENIZ XR 75MG CAP 10''S', '', 'Medicines', 129, '', 'ti-pill', '10''S', false, 3),
  (gen_random_uuid(), 'SUPRACAL OS STRIP OF 10 TABLETS', '', 'Medicines', 220, '', 'ti-pill', '10''S', false, 1),
  (gen_random_uuid(), 'ORASEP GEL BOTTLE 15ML', '', 'Pain Relief', 113, '', 'ti-pill', '15ML', false, 2),
  (gen_random_uuid(), 'FORACORT 200MCG AUTOHALER 200MD', '', 'Medicines', 183, '', 'ti-pill', '200PACKET', false, 1),
  (gen_random_uuid(), 'BECLATE 400MCG ROTACAPS 30''S', '', 'Medicines', 149, '', 'ti-pill', '30BOX', false, 1),
  (gen_random_uuid(), 'AEROCORT FORTE ROTACAPS', '', 'Medicines', 131, '', 'ti-pill', '30 NO''S', false, 1),
  (gen_random_uuid(), 'METHIROZ PLUS CAP 10''S', '', 'Medicines', 172, '', 'ti-pill', '10''S', false, 1),
  (gen_random_uuid(), 'MYCLIN EAR DROPS 10ML', '', 'Cold & Flu', 31, '', 'ti-bottle', '10ML', false, 2),
  (gen_random_uuid(), 'OFLOX 100MG REDIUSE BOTTLE OF 60ML SUSPENSION', '', 'Stationery', 169, '', 'ti-pill', '60ML', false, 3),
  (gen_random_uuid(), 'STEMETIL MD 5MG STRIP OF 15 TABLETS', '', 'Medicines', 196, '', 'ti-pill', '15''S', false, 1),
  (gen_random_uuid(), 'NUROKIND NEXT STRIP OF 10 CAPSULES', '', 'Medicines', 162, '', 'ti-pill', '10''S', false, 1),
  (gen_random_uuid(), 'PLACIDA STRIP OF 10 TABLETS', '', 'Medicines', 90, '', 'ti-pill', '10''S', false, 4),
  (gen_random_uuid(), 'CUTIMEGA C SERUM - 30ML', '', 'Medicines', 1710, '', 'ti-pill', '30ML', false, 1),
  (gen_random_uuid(), 'MOISTUREX CREAM 100GM', '', 'Skin Care', 281, '', 'ti-spray', '100GM', false, 2),
  (gen_random_uuid(), 'FLORA BC DRY SYP', '', 'Medicines', 66, '', 'ti-pill', '60 ML', false, 1),
  (gen_random_uuid(), 'DAFFY WRAP OF 75GM BAR', '', 'Medicines', 199, '', 'ti-pill', '75GM', false, 2),
  (gen_random_uuid(), 'AUGMENTIN DDS SUSPENSION 30ML', '', 'Stationery', 196, '', 'ti-pill', '30ML', false, 2),
  (gen_random_uuid(), 'KIDS PRO CHOCOLATE POWDER 200 GM', '', 'Vitamins', 312, '', 'ti-pill', '200GM', false, 1),
  (gen_random_uuid(), 'DIABORAKSHAK SYP - 200 ML', '', 'Medicines', 168, '', 'ti-pill', '200 ML', false, 1),
  (gen_random_uuid(), 'ASTEROS F 10/160MG STRIP OF 10 TABLETS', '', 'Medicines', 141, '', 'ti-pill', '10''S', false, 2),
  (gen_random_uuid(), 'LEVOCET SYP 60ML 60ML', '', 'Medicines', 104, '', 'ti-pill', '60ML', false, 1),
  (gen_random_uuid(), 'VITANOVA D3 SACHET 1GM', '', 'Medicines', 36, '', 'ti-pill', '1GM', false, 4),
  (gen_random_uuid(), 'ETIZOLA BETA 0.5MG TABLET 10''S', '', 'Medicines', 94, '', 'ti-pill', '10''S', false, 3),
  (gen_random_uuid(), 'METROGYL 400MG TAB 20TAB - 20TAB', '', 'Medicines', 33, '', 'ti-pill', '20TAB', false, 4),
  (gen_random_uuid(), 'LOPEZ 3MG TAB 10''S', '', 'Medicines', 86, '', 'ti-pill', '10''S', false, 3),
  (gen_random_uuid(), 'DERMADEW BABY SHAMPOO - 80ML', '', 'Medicines', 139, '', 'ti-pill', '80ML', false, 1),
  (gen_random_uuid(), 'NUROKIND PLUS RF CAP - 10''S', '', 'Medicines', 122, '', 'ti-pill', '10''S', false, 3),
  (gen_random_uuid(), 'PACIMOL 120MG SUSP 60ML', '', 'Medicines', 39, '', 'ti-pill', '60ML', false, 1),
  (gen_random_uuid(), 'KOFAREST PD SYP 100ML 100ML', '', 'Medicines', 155, '', 'ti-pill', '100ML', false, 1),
  (gen_random_uuid(), 'TRIBEN XT TUBE OF 10GM CREAM', '', 'Skin Care', 87, '', 'ti-spray', '10GM', false, 1),
  (gen_random_uuid(), 'GLIMZAB MP2 - 15TAB', '', 'Medicines', 203, '', 'ti-pill', '15TAB', false, 3),
  (gen_random_uuid(), 'AKULC TAB - 10TAB', '', 'Medicines', 195, '', 'ti-pill', '10TAB', false, 2),
  (gen_random_uuid(), 'CITAL SYP 100ML 100ML', '', 'Medicines', 120, '', 'ti-pill', '100ML', false, 2),
  (gen_random_uuid(), 'HIMALAYA WELLNESS AYURSLIM WEIGHT MANAGEMENT CAPSULES (3X60) BOTTLE OF 60', '', 'Medicines', 340, '', 'ti-pill', '60BOTTLE', false, 1),
  (gen_random_uuid(), 'OLIGOCARE FORTE + - 15TAB', '', 'Medicines', 729, '', 'ti-pill', '15TAB', false, 2),
  (gen_random_uuid(), 'NICARDIA RETARD 20MG  30 TAB  - 30TAB', '', 'Medicines', 160, '', 'ti-pill', '30TAB', false, 8),
  (gen_random_uuid(), 'REMIN TOOTHPASTE-50GM - 50GM', '', 'Medicines', 148, '', 'ti-pill', '50GM', false, 1),
  (gen_random_uuid(), 'SOHA LIQUIGEL 0.18% EYE DROPS 5ML', '', 'Pain Relief', 305, '', 'ti-pill', '5ML', false, 2),
  (gen_random_uuid(), 'PRIMOSA 1000MG STRIP OF 15 CAPSULES', '', 'Medicines', 539, '', 'ti-pill', '15''S', false, 1),
  (gen_random_uuid(), 'LOOKMAN E HAYAT OIL 100 ML', '', 'Medicines', 135, '', 'ti-pill', '100ML', false, 2),
  (gen_random_uuid(), 'AMRUTANJAN BACK PAIN ROLL ON 50ML', '', 'Pain Relief', 94, '', 'ti-pill', '50 ML', false, 4),
  (gen_random_uuid(), 'VOMISTOP 10MG STRIP OF 10 TABLETS', '', 'Medicines', 25, '', 'ti-pill', '10 STRIP', false, 10),
  (gen_random_uuid(), 'VERTIN 16MG STRIP OF 15 TABLETS', '', 'Medicines', 406, '', 'ti-pill', '15''S', false, 1),
  (gen_random_uuid(), 'EMBETA XR 25MG TAB  - 30`S', '', 'Medicines', 136, '', 'ti-pill', '30`S', false, 2),
  (gen_random_uuid(), 'VOGLIBITE GM 1/0.3 TABLET 10''S', '', 'Medicines', 136, '', 'ti-pill', '10''S', false, 1),
  (gen_random_uuid(), 'MOMATE S OINT 20GM', '', 'Medicines', 327, '', 'ti-pill', '20GM', false, 1),
  (gen_random_uuid(), 'NERVIHENZ PLUS TABS - 10TAB', '', 'Medicines', 225, '', 'ti-pill', '10TAB', false, 2),
  (gen_random_uuid(), 'ENAM 2.5MG TABLET', '', 'Medicines', 35, '', 'ti-pill', '15 NO''S', false, 5),
  (gen_random_uuid(), 'TROPAN 2.5MG TABLET 10''S', '', 'Medicines', 121, '', 'ti-pill', '10''S', false, 8),
  (gen_random_uuid(), 'EVARAFT SUSP - 150ML', '', 'Medicines', 210, '', 'ti-pill', '150ML', false, 1),
  (gen_random_uuid(), 'CALPOL 120MG STRAWBERRY FLAVOUR BOTTLE OF 60ML SUSPENSION', '', 'Stationery', 38, '', 'ti-pill', '60ML', false, 3),
  (gen_random_uuid(), 'PILEX TAB 60''S', '', 'Medicines', 234, '', 'ti-pill', '60 NO''S', false, 1),
  (gen_random_uuid(), 'ULTRA D3 4K STRIP OF 30 TABLETS', '', 'Medicines', 178, '', 'ti-pill', '30 NO''S', false, 3),
  (gen_random_uuid(), 'IMMUSTAR DROPS 30ML', '', 'Cold & Flu', 79, '', 'ti-bottle', '30ML', false, 1),
  (gen_random_uuid(), 'CEFUWAY 250 - 10TAB - 10 TAB', '', 'Medicines', 337, '', 'ti-pill', '10 TAB', false, 1),
  (gen_random_uuid(), 'CLINSOL 1% GEL 15GM', '', 'Pain Relief', 92, '', 'ti-pill', '15GM', false, 2),
  (gen_random_uuid(), 'ZANDU BALM 8ML', '', 'Pain Relief', 5, '', 'ti-pill', '8ML', false, 36),
  (gen_random_uuid(), 'ALPROVIT ACTIVE CHOCOLATE FLAVOUR JAR OF 200GM ORAL POWDER', '', 'Vitamins', 372, '', 'ti-pill', '200GM', false, 1),
  (gen_random_uuid(), 'RAMITORVA CAPSULE 10''S', '', 'Medicines', 58, '', 'ti-pill', '10''S', false, 3),
  (gen_random_uuid(), 'MOSI EYE DROPS 5ML', '', 'Cold & Flu', 115, '', 'ti-bottle', '5ML', false, 1),
  (gen_random_uuid(), 'LIVOGEN Z TAB STRIP 15 NO''S', '', 'Medicines', 109, '', 'ti-pill', '15 NO''S', false, 2),
  (gen_random_uuid(), 'BRONKOLYTE DX SYRUP 100ML', '', 'Cold & Flu', 115, '', 'ti-bottle', '100ML', false, 2),
  (gen_random_uuid(), 'DKF SYP - 100 ML', '', 'Medicines', 103, '', 'ti-pill', '100 ML', false, 1),
  (gen_random_uuid(), 'CETZINE SYP 60ML', '', 'Medicines', 42, '', 'ti-pill', '60ML', false, 3),
  (gen_random_uuid(), 'HANSEPRAN 100MG CAPSULE', '', 'Medicines', 42, '', 'ti-pill', '10''S', false, 6),
  (gen_random_uuid(), 'NEBZMART FB 1MG SMARTULES 7*2ML', '', 'Medicines', 531, '', 'ti-pill', '2ML', false, 5),
  (gen_random_uuid(), 'ANDREAS GLUCOSE-D  ORAN -120GM - 120GM', '', 'Medicines', 43, '', 'ti-pill', '120GM', false, 13),
  (gen_random_uuid(), 'UTISER SYP -100ML - 100 ML', '', 'Medicines', 119, '', 'ti-pill', '100 ML', false, 3),
  (gen_random_uuid(), 'KETO MINE DT -15TAB - 15TAB', '', 'Medicines', 117, '', 'ti-pill', '15TAB', false, 5),
  (gen_random_uuid(), 'DIARACLEAN-PLUS TAB - 10TAB', '', 'Medicines', 67, '', 'ti-pill', '10TAB', false, 10),
  (gen_random_uuid(), 'DARMEE K-10 MG CREAM - 15GM', '', 'Skin Care', 102, '', 'ti-spray', '15GM', false, 5),
  (gen_random_uuid(), 'AARJE ME -  20CAP OMEE - 20C', '', 'Medicines', 55, '', 'ti-pill', '20C', false, 35),
  (gen_random_uuid(), 'T MINIC SYP 60ML BOTTLE 60ML', '', 'Medicines', 125, '', 'ti-pill', '60ML', false, 1),
  (gen_random_uuid(), 'SUNSHOT GEL SPF-50 - 100GM', '', 'Pain Relief', 450, '', 'ti-pill', '100GM', false, 1),
  (gen_random_uuid(), 'ELOSONE HT CREAM 25GM', '', 'Skin Care', 165, '', 'ti-spray', '25GM', false, 2),
  (gen_random_uuid(), 'ELOSONE HT CREAM 15GM', '', 'Skin Care', 150, '', 'ti-spray', '15GM', false, 3),
  (gen_random_uuid(), 'CLOPIZEN A 150 TABLET 10 NO''S', '', 'Medicines', 37, '', 'ti-pill', '10''S', false, 10),
  (gen_random_uuid(), 'SUNROOF LOTION  SPF-50  100ML - 100ML', '', 'Skin Care', 395, '', 'ti-spray', '100ML', false, 3),
  (gen_random_uuid(), 'OMNIGEL GEL 75GM', '', 'Pain Relief', 262, '', 'ti-pill', '75GM', false, 2),
  (gen_random_uuid(), 'OMNIGEL SPRAY 55GM', '', 'Pain Relief', 247, '', 'ti-pill', '55GM', false, 1),
  (gen_random_uuid(), 'OMNIGEL GEL 20GM', '', 'Pain Relief', 107, '', 'ti-pill', '20GM', false, 2),
  (gen_random_uuid(), 'CADILA ORS ORANGE POWDER 21GM', '', 'Vitamins', 23, '', 'ti-pill', '21GM', false, 90),
  (gen_random_uuid(), 'KETOKEM SHAMPOO 110ML', '', 'Medicines', 9, '', 'ti-pill', '110 ML', false, 10),
  (gen_random_uuid(), 'GLIMP M 1MG STRIP OF 10 TABLETS', '', 'Medicines', 120, '', 'ti-pill', '10''S', false, 14),
  (gen_random_uuid(), 'AMLIP 5MG TABLET 10''S', '', 'Medicines', 27, '', 'ti-pill', '10''S', false, 9),
  (gen_random_uuid(), 'ZUBITIN 10MG TABLET', '', 'Medicines', 378, '', 'ti-pill', '30 NO''S', false, 1),
  (gen_random_uuid(), 'SOHA 0.1% EYE DROPS 5ML', '', 'Cold & Flu', 233, '', 'ti-bottle', '5ML', false, 1),
  (gen_random_uuid(), 'ENCORATE SYP 200ML 200ML', '', 'Medicines', 139, '', 'ti-pill', '200ML', false, 1),
  (gen_random_uuid(), 'CARVISTAR 3.125MG STRIP OF 15 TABLETS', '', 'Medicines', 61, '', 'ti-pill', '15''S', false, 5),
  (gen_random_uuid(), 'SANDU SHISHUVIN BALKADU 200ML', '', 'Medicines', 150, '', 'ti-pill', '200ML', false, 2),
  (gen_random_uuid(), 'SANDU SHISHUVIN SYRUP 100 ML', '', 'Cold & Flu', 84, '', 'ti-bottle', '100ML', false, 1),
  (gen_random_uuid(), 'CONOZOL SHAMPOO 100ML  - 100 ML', '', 'Medicines', 253, '', 'ti-pill', '100 ML', false, 1),
  (gen_random_uuid(), 'METHYL SALICYLATE SOLUTION - 100ML', '', 'Medicines', 135, '', 'ti-pill', '100ML', false, 1),
  (gen_random_uuid(), 'ACNESTAR 2.5% SOAP 75GM', '', 'Skin Care', 97, '', 'ti-spray', '75GM', false, 2),
  (gen_random_uuid(), 'GEMCAL CAP 15`S', '', 'Medicines', 392, '', 'ti-pill', '15`S', false, 5),
  (gen_random_uuid(), 'CHAPTEX LIP BALM 10GM', '', 'Pain Relief', 195, '', 'ti-pill', '10GM', false, 1),
  (gen_random_uuid(), 'AQUASOFT FC ADVANCED CREAM 100GM', '', 'Skin Care', 448, '', 'ti-spray', '100GM', false, 1),
  (gen_random_uuid(), 'CLINFRESH SOAP 75 G', '', 'Skin Care', 66, '', 'ti-spray', '75GM', false, 5),
  (gen_random_uuid(), 'BECOSULES CAP 20`S 20`S', '', 'Medicines', 62, '', 'ti-pill', '20`S', false, 3),
  (gen_random_uuid(), 'KETO B CREAM 10GM', '', 'Skin Care', 149, '', 'ti-spray', '10GM', false, 1),
  (gen_random_uuid(), 'SUCRALHENZ SYP - 200ML', '', 'Medicines', 411, '', 'ti-pill', '200ML', false, 1),
  (gen_random_uuid(), 'LOBACHEK 5MG TAB 10''S', '', 'Medicines', 58, '', 'ti-pill', '10''S', false, 6),
  (gen_random_uuid(), 'VOGLI RAPID 0.3/0.5 TAB 10''S', '', 'Medicines', 159, '', 'ti-pill', '10 NO''S', false, 3),
  (gen_random_uuid(), 'GLYCOMET SR 500MG STRIP OF 20 TABLETS', '', 'Medicines', 42, '', 'ti-pill', '20 NO''S', false, 6),
  (gen_random_uuid(), 'ZERODOL TH 4MG TABLET 10''S', '', 'Medicines', 275, '', 'ti-pill', '10''S', false, 1),
  (gen_random_uuid(), 'MCLAZIDE + M STRIP OF 15 TABLETS', '', 'Medicines', 143, '', 'ti-pill', '15''S', false, 5),
  (gen_random_uuid(), 'SARPOT AM 15TAB - 15TAB', '', 'Medicines', 108, '', 'ti-pill', '15TAB', false, 2),
  (gen_random_uuid(), 'NUSOWIN ADULT VANILLA POWDER 200 G', '', 'Vitamins', 349, '', 'ti-pill', '200GM', false, 1),
  (gen_random_uuid(), 'GLIMESTAR M 2 15TAB - 15TAB', '', 'Medicines', 162, '', 'ti-pill', '15TAB', false, 1),
  (gen_random_uuid(), 'SPORIDEX 250MG REDIMIX 30ML 30ML', '', 'Medicines', 143, '', 'ti-pill', '30ML', false, 1),
  (gen_random_uuid(), 'BIOSIA 1000MG TAB - 10TAB', '', 'Medicines', 457, '', 'ti-pill', '10TAB', false, 3),
  (gen_random_uuid(), 'FOMIRA EYE DROP 10ML', '', 'Cold & Flu', 445, '', 'ti-bottle', '10ML', false, 1),
  (gen_random_uuid(), 'R4CLEAR TABS - 10TAB', '', 'Medicines', 235, '', 'ti-pill', '10TAB', false, 3),
  (gen_random_uuid(), 'OLOPLUS OD EYE DROPS 3ML', '', 'Cold & Flu', 214, '', 'ti-bottle', '3ML', false, 2),
  (gen_random_uuid(), 'LOTEPRED LS 0.2% EYE DROPS 5ML', '', 'Cold & Flu', 159, '', 'ti-bottle', '5 ML', false, 2),
  (gen_random_uuid(), 'SITAMAX 50 MG TABLET 10 NO''S', '', 'Medicines', 143, '', 'ti-pill', '10''S', false, 2),
  (gen_random_uuid(), 'GIBTULIO 10 STRIP OF 10 TABLETS', '', 'Medicines', 159, '', 'ti-pill', '10''S', false, 2),
  (gen_random_uuid(), 'GLIMY 1MG STRIP OF 10 TABLETS', '', 'Medicines', 154, '', 'ti-pill', '10''S', false, 1),
  (gen_random_uuid(), 'MEXT 7.5MG TABLET 10''S', '', 'Medicines', 90, '', 'ti-pill', '10''S', false, 1),
  (gen_random_uuid(), 'ETOVA ER 600MG TABLET', '', 'Medicines', 273, '', 'ti-pill', '10 NO''S', false, 1),
  (gen_random_uuid(), 'MITOCAL CT STRIP OF 15 SOFTGEL CAPSULES', '', 'Pain Relief', 150, '', 'ti-pill', '15''S', false, 1),
  (gen_random_uuid(), 'AQVIKO M 10 TAB - 10TAB', '', 'Medicines', 149, '', 'ti-pill', '10TAB', false, 1),
  (gen_random_uuid(), 'CILIX 10MG STRIP OF 15 TABLETS', '', 'Medicines', 91, '', 'ti-pill', '15''S', false, 2),
  (gen_random_uuid(), 'FEBUDAY 40MG TABLET 10''S', '', 'Medicines', 116, '', 'ti-pill', '10''S', false, 1),
  (gen_random_uuid(), 'LANUM 667MG TABLET', '', 'Medicines', 75, '', 'ti-pill', '10 NO''S', false, 4),
  (gen_random_uuid(), 'TRIORAGLIM 2MG TAB - 15TAB', '', 'Medicines', 187, '', 'ti-pill', '15TAB', false, 1),
  (gen_random_uuid(), 'VIVADAPA TRIO TAB - 10TAB', '', 'Medicines', 225, '', 'ti-pill', '10TAB', false, 3),
  (gen_random_uuid(), 'FEXANTO ER 40 STRIP OF 10 TABLETS', '', 'Medicines', 141, '', 'ti-pill', '10''S', false, 2),
  (gen_random_uuid(), 'MCLAZIDE 80MG STRIP OF 15 TABLETS', '', 'Medicines', 91, '', 'ti-pill', '15''S', false, 4),
  (gen_random_uuid(), 'LEOTOR 100 - 10TAB', '', 'Medicines', 273, '', 'ti-pill', '10TAB', false, 2),
  (gen_random_uuid(), 'NARCODOL TAB 10''S', '', 'Medicines', 121, '', 'ti-pill', '10''S', false, 1),
  (gen_random_uuid(), 'CALCIMAX D SYP 200ML 200ML', '', 'Medicines', 169, '', 'ti-pill', '200ML', false, 1),
  (gen_random_uuid(), 'PIOPAR GZ TOTAL TAB - 15TAB', '', 'Medicines', 140, '', 'ti-pill', '15TAB', false, 8),
  (gen_random_uuid(), 'PAUSE 500MG TABLET 10''S', '', 'Medicines', 198, '', 'ti-pill', '10''S', false, 1),
  (gen_random_uuid(), 'AMANZA MV 1MG STRIP OF 10 TABLETS', '', 'Medicines', 108, '', 'ti-pill', '10''S', false, 7),
  (gen_random_uuid(), 'COVERSYL PLUS STRIP OF 10 TABLETS', '', 'Medicines', 264, '', 'ti-pill', '10''S', false, 3),
  (gen_random_uuid(), 'FLAVEDON OD 80MG STRIP OF 10 CAPSULES', '', 'Medicines', 328, '', 'ti-pill', '10''S', false, 1),
  (gen_random_uuid(), 'ROSUMAC 5MG STRIP OF 15 TABLETS', '', 'Medicines', 166, '', 'ti-pill', '15''S', false, 2),
  (gen_random_uuid(), 'TELMA 20MG TAB 30``S 30`S', '', 'Medicines', 124, '', 'ti-pill', '30`S', false, 1),
  (gen_random_uuid(), 'NEBI 2.5MG TABLET 10''S', '', 'Medicines', 80, '', 'ti-pill', '10''S', false, 1),
  (gen_random_uuid(), 'NEXPRO JUNIOR SACH 1GM', '', 'Medicines', 27, '', 'ti-pill', '1GM', false, 6),
  (gen_random_uuid(), 'ELTROXIN 25MG TAB - 120BOTTLE', '', 'Medicines', 185, '', 'ti-pill', '120BOTTLE', false, 1),
  (gen_random_uuid(), 'SHELCAL XT STRIP OF 15 TABLETS', '', 'Medicines', 402, '', 'ti-pill', '15''S', false, 1),
  (gen_random_uuid(), 'TRIPRIDE 1MG TAB 10''S', '', 'Medicines', 220, '', 'ti-pill', '10''S', false, 1),
  (gen_random_uuid(), 'DENTABLIST GEL 80 G', '', 'Pain Relief', 210, '', 'ti-pill', '80GM', false, 1),
  (gen_random_uuid(), 'RAMISTAR 2.5MG TAB - 15`S', '', 'Medicines', 83, '', 'ti-pill', '15`S', false, 4),
  (gen_random_uuid(), 'BUNASE 1MG RESPULES 2ML', '', 'Medicines', 127, '', 'ti-pill', '2ML', false, 2),
  (gen_random_uuid(), 'MONTEK LC TAB  - 15TAB', '', 'Medicines', 368, '', 'ti-pill', '15TAB', false, 2),
  (gen_random_uuid(), 'CALCIMAX P SUSP 200ML - 200ML', '', 'Medicines', 175, '', 'ti-pill', '200ML', false, 6),
  (gen_random_uuid(), 'HIMALAYA BRESOL TABLETS - 60''S', '', 'Medicines', 215, '', 'ti-pill', '60BOTTLE', false, 1),
  (gen_random_uuid(), 'KAYAM TAB 10''S', '', 'Medicines', 42, '', 'ti-pill', '10''S', false, 1),
  (gen_random_uuid(), 'KOZISOL FACE WASH - 100 G', '', 'Skin Care', 316, '', 'ti-spray', '100 G', false, 1),
  (gen_random_uuid(), 'ATARAX 10MG TAB 15`S', '', 'Medicines', 60, '', 'ti-pill', '15`S', false, 8),
  (gen_random_uuid(), 'STAMLO 2.5MG TABLET 30''S', '', 'Medicines', 57, '', 'ti-pill', '30''S', false, 1),
  (gen_random_uuid(), 'LEVOFLOX 500MG TABLET', '', 'Medicines', 96, '', 'ti-pill', '10 NO''S', false, 1),
  (gen_random_uuid(), 'KETOROL DT - 15 NO''S', '', 'Medicines', 183, '', 'ti-pill', '15 NO''S', false, 1),
  (gen_random_uuid(), 'GLIMESTAR M1 15TAB - 15TAB', '', 'Medicines', 112, '', 'ti-pill', '15TAB', false, 3),
  (gen_random_uuid(), 'CLAVAM FORTE DRY SYP 30ML 30ML', '', 'Medicines', 183, '', 'ti-pill', '30ML', false, 1),
  (gen_random_uuid(), 'BENITOWA 4MG STRIP OF 15 TABLETS', '', 'Medicines', 149, '', 'ti-pill', '15''S', false, 3),
  (gen_random_uuid(), 'DELPOCALM DROPS 10ML', '', 'Cold & Flu', 49, '', 'ti-bottle', '10ML', false, 1),
  (gen_random_uuid(), 'LOBAZAM MD 5MG TAB 10''S', '', 'Medicines', 61, '', 'ti-pill', '10''S', false, 1),
  (gen_random_uuid(), 'AZEE 500MG TAB 3`S 3`S', '', 'Medicines', 76, '', 'ti-pill', '3`S', false, 5),
  (gen_random_uuid(), 'SHY NM TUBE OF 50GM TOOTHPASTE', '', 'Medicines', 178, '', 'ti-pill', '50GM', false, 1),
  (gen_random_uuid(), 'CALPOL 250MG SUSP 60ML 60ML', '', 'Medicines', 43, '', 'ti-pill', '60ML', false, 5),
  (gen_random_uuid(), 'OVA ARK - 100ML', '', 'Medicines', 80, '', 'ti-pill', '100ML', false, 1),
  (gen_random_uuid(), 'FLATKIN SILICONE GEL 10GM', '', 'Pain Relief', 550, '', 'ti-pill', '10GM', false, 1),
  (gen_random_uuid(), 'STAMLO 5MG TAB - 30TAB', '', 'Medicines', 80, '', 'ti-pill', '30TAB', false, 8),
  (gen_random_uuid(), 'VALPARIN CHRONO 200MG STRIP OF 15 TABLETS', '', 'Medicines', 149, '', 'ti-pill', '15''S', false, 2),
  (gen_random_uuid(), 'LEVOCET M BOTTLE OF 30ML SYRUP', '', 'Cold & Flu', 125, '', 'ti-bottle', '30ML', false, 2),
  (gen_random_uuid(), 'ARBIVIT 3 DROPS 15ML', '', 'Cold & Flu', 96, '', 'ti-bottle', '15ML', false, 3),
  (gen_random_uuid(), 'CARDIROSE GOLD 10 STRIP OF 10 CAPSULES', '', 'Medicines', 217, '', 'ti-pill', '10''S', false, 3),
  (gen_random_uuid(), 'DICLOWIN MR INSTANT PAIN RELIEF BOTTLE OF 40GM SPRAY', '', 'Pain Relief', 79, '', 'ti-pill', '40GM', false, 6),
  (gen_random_uuid(), 'RATOL CAKE - 25GM', '', 'Medicines', 20, '', 'ti-pill', '25GM', false, 6),
  (gen_random_uuid(), 'HAIRSHEILD LIQUID - 30ML', '', 'Medicines', 71, '', 'ti-pill', '30ML', false, 4),
  (gen_random_uuid(), 'ONDERO MET 2.5MG/500MG 10''S', '', 'Medicines', 147, '', 'ti-pill', '10''S', false, 3),
  (gen_random_uuid(), 'TERBINAFORCE 250MG STRIP OF 7 TABLETS', '', 'Medicines', 125, '', 'ti-pill', '7''S', false, 2),
  (gen_random_uuid(), 'ERITEL AM 40 TABS 15''S', '', 'Medicines', 282, '', 'ti-pill', '15 NO''S', false, 1),
  (gen_random_uuid(), 'ABIWAYS STRIP OF 15 TABLETS', '', 'Medicines', 246, '', 'ti-pill', '15''S', false, 4),
  (gen_random_uuid(), 'OSTEOFOS 70MG TABLET 4''S', '', 'Medicines', 355, '', 'ti-pill', '4''S', false, 1),
  (gen_random_uuid(), 'GABAPIN 100MG STRIP OF 15 TABLETS', '', 'Medicines', 154, '', 'ti-pill', '15 NO''S', false, 1),
  (gen_random_uuid(), 'ERYTHRO 250MG TABLET', '', 'Medicines', 56, '', 'ti-pill', '10''S', false, 15),
  (gen_random_uuid(), 'NOR TZ TAB 6''S', '', 'Medicines', 40, '', 'ti-pill', '6''S', false, 10),
  (gen_random_uuid(), 'MELAMET CREAM 15GM', '', 'Skin Care', 85, '', 'ti-spray', '15 GRAM', false, 3),
  (gen_random_uuid(), 'ZINVITAL TAB 10''S', '', 'Medicines', 98, '', 'ti-pill', '10''S', false, 1),
  (gen_random_uuid(), 'GLYCOMET 500MG STRIP OF 10 TABLETS', '', 'Medicines', 19, '', 'ti-pill', '10`S', false, 3),
  (gen_random_uuid(), 'PANKREOFLAT STRIP OF 15 TABLETS', '', 'Medicines', 307, '', 'ti-pill', '15''S', false, 1),
  (gen_random_uuid(), 'SUJAT CAP 10''S', '', 'Medicines', 89, '', 'ti-pill', '10''S', false, 1),
  (gen_random_uuid(), 'ASTHALIN 2MG STRIP OF 45 TABLETS', '', 'Medicines', 13, '', 'ti-pill', '45 STRIP', false, 1),
  (gen_random_uuid(), 'DERMIFORD CREAM 15GM TUBE 15GM', '', 'Skin Care', 102, '', 'ti-spray', '15GM', false, 3),
  (gen_random_uuid(), 'SUNROOF LOTION - 60ML', '', 'Skin Care', 249, '', 'ti-spray', '60ML', false, 1),
  (gen_random_uuid(), 'CILACAR 10MG TAB - 15`S', '', 'Medicines', 219, '', 'ti-pill', '15`S', false, 1),
  (gen_random_uuid(), 'GABANEURON NT 100/10MG STRIP OF 15 TABLETS', '', 'Medicines', 196, '', 'ti-pill', '15''S', false, 2),
  (gen_random_uuid(), 'OVABD TABLET 10''S', '', 'Medicines', 342, '', 'ti-pill', '10''S', false, 1),
  (gen_random_uuid(), 'NEW SHY NM TOOTHPASTE - 100GM', '', 'Medicines', 312, '', 'ti-pill', '100GM', false, 1),
  (gen_random_uuid(), 'KESHROOT HAIR OIL - 100 ML', '', 'Medicines', 160, '', 'ti-pill', '100 ML', false, 2),
  (gen_random_uuid(), 'INHB TAB - 10TAB', '', 'Medicines', 174, '', 'ti-pill', '10TAB', false, 5),
  (gen_random_uuid(), 'TELMA 20MG STRIP OF 30 TABLETS', '', 'Medicines', 121, '', 'ti-pill', '30''S', false, 2),
  (gen_random_uuid(), 'HOMO 16 D TABLET 15''S', '', 'Medicines', 319, '', 'ti-pill', '15 NO''S', false, 3),
  (gen_random_uuid(), 'MEFTAL FORTE TABS - 10 S', '', 'Medicines', 43, '', 'ti-pill', '10 S', false, 3),
  (gen_random_uuid(), 'CLAVAM BID 228.5MG DRY SYP 30ML', '', 'Medicines', 65, '', 'ti-pill', '30ML', false, 3),
  (gen_random_uuid(), 'SMARTAID DISPOSABLE SKIN BLAD - 1PC', '', 'Medicines', 50, '', 'ti-pill', '1PC', false, 10),
  (gen_random_uuid(), 'BUDESCORE RESPULES - 2ML', '', 'Medicines', 125, '', 'ti-pill', '2ML', false, 10),
  (gen_random_uuid(), 'DUOSCORE RESPULES - 3ML', '', 'Medicines', 115, '', 'ti-pill', '3ML', false, 10),
  (gen_random_uuid(), 'SPORIDEX CV 375MG STRIP OF 10 TABLETS', '', 'Medicines', 244, '', 'ti-pill', '10''S', false, 2),
  (gen_random_uuid(), 'BORIC ACID POWDER 50GM', '', 'Vitamins', 35, '', 'ti-pill', '50GM', false, 6),
  (gen_random_uuid(), 'BORIC ACID POWDER 100GM', '', 'Vitamins', 80, '', 'ti-pill', '100GM', false, 3),
  (gen_random_uuid(), 'BORIC ACID POWDER 20 GM', '', 'Vitamins', 15, '', 'ti-pill', '20GM', false, 3),
  (gen_random_uuid(), 'TIL OIL TAIL - 100 ML', '', 'Medicines', 90, '', 'ti-pill', '100 ML', false, 2),
  (gen_random_uuid(), 'HYDROGEN PEROXIDE SOLUTION 25ML', '', 'Medicines', 12, '', 'ti-pill', '25 MILLILITRE', false, 3),
  (gen_random_uuid(), 'FLORITE SUPER POWDER PUFF   - 1PIC', '', 'Vitamins', 140, '', 'ti-pill', '1PIC', false, 4),
  (gen_random_uuid(), 'FLYING TIGER CUB BALM 15GM - 15 GM', '', 'Pain Relief', 75, '', 'ti-pill', '15 GM', false, 13),
  (gen_random_uuid(), 'NEVLON MAX TUBE OF 150GM CREAM', '', 'Skin Care', 333, '', 'ti-spray', '150GM', false, 1),
  (gen_random_uuid(), 'TEDIBAR BABY SOAP BOX OF 100 G X 2 200GM', '', 'Skin Care', 268, '', 'ti-spray', '200GM', false, 3),
  (gen_random_uuid(), 'GELUSIL MPS ORIGINAL MINT FLAVOUR TABLET 15''S', '', 'Pain Relief', 27, '', 'ti-pill', '15''S', false, 4),
  (gen_random_uuid(), 'SOFIRASH CREAM 30GM', '', 'Skin Care', 155, '', 'ti-spray', '30GM', false, 1),
  (gen_random_uuid(), 'FLUCOLD TABLET 10''S', '', 'Cold & Flu', 50, '', 'ti-bottle', '10''S', false, 2),
  (gen_random_uuid(), 'QUTAN 25MG TABLET 10''S', '', 'Medicines', 75, '', 'ti-pill', '10''S', false, 3),
  (gen_random_uuid(), 'ZIFI 50MG DRY SYP 30ML', '', 'Medicines', 52, '', 'ti-pill', '30ML', false, 1),
  (gen_random_uuid(), 'SAT ISABGOL DEER - 50GM', '', 'Medicines', 130, '', 'ti-pill', '50GM', false, 3),
  (gen_random_uuid(), 'RANAKPUR SAT ISABGOL 50GM', '', 'Medicines', 100, '', 'ti-pill', '50GM', false, 3),
  (gen_random_uuid(), 'SOFRAMYCIN SKIN CREAM - 30GM', '', 'Skin Care', 53, '', 'ti-spray', '30GM', false, 3),
  (gen_random_uuid(), 'RABEKIND DSR STRIP OF 10 CAPSULES', '', 'Medicines', 116, '', 'ti-pill', '10''S', false, 1),
  (gen_random_uuid(), 'DEXORANGE CAP - 30 NO''S', '', 'Medicines', 193, '', 'ti-pill', '30 NO''S', false, 2),
  (gen_random_uuid(), 'CEFTAS 200MG STRIP OF 10 TABLETS', '', 'Medicines', 99, '', 'ti-pill', '10''S', false, 2),
  (gen_random_uuid(), 'FOLVITE MB TABLET 3 X 15 NO''S', '', 'Medicines', 262, '', 'ti-pill', '15''S', false, 3),
  (gen_random_uuid(), 'LULICAN CREAM 30GM', '', 'Skin Care', 159, '', 'ti-spray', '30GM', false, 1),
  (gen_random_uuid(), 'DEROBIN OINT 30GM', '', 'Medicines', 131, '', 'ti-pill', '30GM', false, 3),
  (gen_random_uuid(), 'AARJE FEROL -  4CAP - 4CAP', '', 'Medicines', 106, '', 'ti-pill', '4CAP', false, 10),
  (gen_random_uuid(), 'AARJE GRA PLUS 100 MG - 4TAB - 4TAB', '', 'Medicines', 328, '', 'ti-pill', '4TAB', false, 4),
  (gen_random_uuid(), 'AARJEPAN 40 AB - 10TAB', '', 'Medicines', 76, '', 'ti-pill', '10TAB', false, 20),
  (gen_random_uuid(), 'CALAMINE IM LOTION 100ML', '', 'Skin Care', 137, '', 'ti-spray', '100ML', false, 2),
  (gen_random_uuid(), 'GASCAP SUGAR FREE BOTTLE OF 170ML SUSPENSION', '', 'Stationery', 150, '', 'ti-pill', '170ML', false, 1),
  (gen_random_uuid(), 'DOFOTIL SYRUP - 200ML', '', 'Cold & Flu', 262, '', 'ti-bottle', '200ML', false, 1),
  (gen_random_uuid(), 'KETO AZ SOLUTION 125ml - 125ml', '', 'Medicines', 452, '', 'ti-pill', '125ML', false, 2),
  (gen_random_uuid(), 'ENERZAL ORANGE LIQUID 200ML', '', 'Vitamins', 40, '', 'ti-pill', '200ML', false, 18),
  (gen_random_uuid(), 'OLMARK 20MG TAB 15''S', '', 'Medicines', 210, '', 'ti-pill', '15''S', false, 1),
  (gen_random_uuid(), 'OSSOPAN D SUSP 200ML', '', 'Medicines', 186, '', 'ti-pill', '200 ML', false, 1),
  (gen_random_uuid(), 'TOFATAS XR  TAB - 10S', '', 'Medicines', 422, '', 'ti-pill', '10S', false, 1),
  (gen_random_uuid(), 'L MONTUS SUS 60ML', '', 'Medicines', 129, '', 'ti-pill', '60ML', false, 2),
  (gen_random_uuid(), 'ROSIMIT F 10 CAP - 15CAP', '', 'Medicines', 175, '', 'ti-pill', '15CAP', false, 2),
  (gen_random_uuid(), 'CYBLEX M 30 XR TAB 15''S', '', 'Medicines', 137, '', 'ti-pill', '15''S', false, 4),
  (gen_random_uuid(), 'DEXOLAC 2 FOLLOW UP FORMULA POWDER 400 G TIN 400GM', '', 'Vitamins', 465, '', 'ti-pill', '400GM', false, 1),
  (gen_random_uuid(), 'SEBAMED BABY MASSAGE OIL - 150ML', '', 'Medicines', 471, '', 'ti-pill', '150ML', false, 1),
  (gen_random_uuid(), 'THIOTOP GEL - 30 GM', '', 'Pain Relief', 206, '', 'ti-pill', '30 GM', false, 1),
  (gen_random_uuid(), 'KUSHAL KANTHIL TAB 1''S', '', 'Medicines', 72, '', 'ti-pill', '1''S', false, 2),
  (gen_random_uuid(), 'DIVAA OD 500 15TAB - 15TAB', '', 'Medicines', 281, '', 'ti-pill', '15TAB', false, 5),
  (gen_random_uuid(), 'KEPPRA 500MG TABLET 10''S', '', 'Medicines', 139, '', 'ti-pill', '10''S', false, 4),
  (gen_random_uuid(), 'APTAMIL STAGE 1 INFANT FORMULA POWDER WITH PREBIOTICS (UPTO 6 MONTHS) - 400G REFILL', '', 'Vitamins', 750, '', 'ti-pill', '400GM', false, 1),
  (gen_random_uuid(), 'MOKTEL DROPS 30ML', '', 'Cold & Flu', 130, '', 'ti-bottle', '30ML', false, 1),
  (gen_random_uuid(), 'APTIVATE SYP SMALL 175ML 175ML', '', 'Medicines', 174, '', 'ti-pill', '175ML', false, 1),
  (gen_random_uuid(), 'SOFTOVAC CONSTIPATION RELIEF POWDER BOTTLE OF 100 G', '', 'Vitamins', 211, '', 'ti-pill', '100 G', false, 1),
  (gen_random_uuid(), 'MUCOPAIN 20% GEL 15GM', '', 'Pain Relief', 87, '', 'ti-pill', '15GM', false, 1),
  (gen_random_uuid(), 'REPACE 25MG TABLET 10''S', '', 'Medicines', 55, '', 'ti-pill', '10''S', false, 3),
  (gen_random_uuid(), 'PREDMET 8MG STRIP OF 15 TABLETS', '', 'Medicines', 107, '', 'ti-pill', '15''S', false, 1),
  (gen_random_uuid(), 'LICEL OIL 40ML', '', 'Medicines', 150, '', 'ti-pill', '40ML', false, 1),
  (gen_random_uuid(), 'MAHA NARAYAN TAIL - 100ML', '', 'Medicines', 200, '', 'ti-pill', '100ML', false, 1),
  (gen_random_uuid(), 'DERIPHYLLIN TAB 30''S', '', 'Medicines', 26, '', 'ti-pill', '30 NO''S', false, 2),
  (gen_random_uuid(), 'DERIPHYLLIN RETARD 150MG TAB 30`S 30`S', '', 'Medicines', 42, '', 'ti-pill', '30`S', false, 2),
  (gen_random_uuid(), 'GLUCOSE D POWDER 200GM', '', 'Vitamins', 85, '', 'ti-pill', '200 GRAM', false, 2),
  (gen_random_uuid(), 'GLUCOSE D ORANGE POWDER 100GM', '', 'Vitamins', 50, '', 'ti-pill', '100GM', false, 3),
  (gen_random_uuid(), 'TELISMART 40 TAB - 15TAB', '', 'Medicines', 108, '', 'ti-pill', '15TAB', false, 8),
  (gen_random_uuid(), 'LIMCEE ZINC CHOW TAB - 15 TAB', '', 'Medicines', 73, '', 'ti-pill', '15 TAB', false, 3),
  (gen_random_uuid(), 'COLDCAP CAPSULE 15 NO''S', '', 'Cold & Flu', 30, '', 'ti-bottle', '15''S', false, 6),
  (gen_random_uuid(), 'OFLOTAS 200MG TABLET 10''S', '', 'Medicines', 81, '', 'ti-pill', '10''S', false, 6),
  (gen_random_uuid(), 'DICLOGEM MR TAB 10`S', '', 'Medicines', 98, '', 'ti-pill', '10`S', false, 5),
  (gen_random_uuid(), 'OMNICLAV 375MG TABLET 6''S', '', 'Medicines', 148, '', 'ti-pill', '6''S', false, 3),
  (gen_random_uuid(), 'PANTOSEC 40MG TABLET 10''S', '', 'Medicines', 148, '', 'ti-pill', '10''S', false, 3),
  (gen_random_uuid(), 'OKACET 10MG TABLET', '', 'Medicines', 20, '', 'ti-pill', '10''S', false, 17),
  (gen_random_uuid(), 'TELMA H 40MG STRIP OF 15 TABLETS', '', 'Medicines', 345, '', 'ti-pill', '15''S', false, 2),
  (gen_random_uuid(), 'OLMESAR CH 20MG STRIP OF 15 TABLETS', '', 'Medicines', 235, '', 'ti-pill', '15''S', false, 1),
  (gen_random_uuid(), 'DOMSTAL BABY BOTTLE OF 5ML ORAL DROPS', '', 'Cold & Flu', 99, '', 'ti-bottle', '5ML', false, 1),
  (gen_random_uuid(), 'ATORVA 40 - 10TAB', '', 'Medicines', 206, '', 'ti-pill', '10TAB', false, 1),
  (gen_random_uuid(), 'TELMA 40MG 15 TAB - 15TAB', '', 'Medicines', 106, '', 'ti-pill', '15TAB', false, 2),
  (gen_random_uuid(), 'ROSEDAY GOLD TAB 10''S', '', 'Medicines', 168, '', 'ti-pill', '10''S', false, 1),
  (gen_random_uuid(), 'GLYCOMET GP STAR 2MG TABS - 10TAB', '', 'Medicines', 152, '', 'ti-pill', '10TAB', false, 1),
  (gen_random_uuid(), 'PIOZ 15MG TAB - 10TAB', '', 'Medicines', 79, '', 'ti-pill', '10TAB', false, 1),
  (gen_random_uuid(), 'FEMITE LOTION 3 X 9 ML', '', 'Skin Care', 277, '', 'ti-spray', '9ML', false, 1),
  (gen_random_uuid(), 'COLICAID DROPS 15ML 15ML', '', 'Cold & Flu', 66, '', 'ti-bottle', '15ML', false, 1),
  (gen_random_uuid(), 'CIPLAR LA 20MG TAB 15``S 15`S', '', 'Medicines', 64, '', 'ti-pill', '15`S', false, 1),
  (gen_random_uuid(), 'TRICIUM XT BOTTLE OF 30 TABLETS', '', 'Medicines', 360, '', 'ti-pill', '30BOTTLE', false, 1),
  (gen_random_uuid(), 'VIBACT DS CAP 10`S', '', 'Medicines', 220, '', 'ti-pill', '10`S', false, 1),
  (gen_random_uuid(), 'DR. BISWAS GOOD HEALTH CAPSULE 50', '', 'Medicines', 256, '', 'ti-pill', '50BOTTLE', false, 1),
  (gen_random_uuid(), 'WAYO BIS TABLET 10''S', '', 'Medicines', 284, '', 'ti-pill', '10''S', false, 1),
  (gen_random_uuid(), 'FREY-NEBI AM TAB - 10TAB', '', 'Medicines', 93, '', 'ti-pill', '10TAB', false, 4),
  (gen_random_uuid(), 'ZINCOVIT SYP 200ML', '', 'Medicines', 160, '', 'ti-pill', '200ML', false, 2),
  (gen_random_uuid(), 'BESTCAL HD TAB - 15S', '', 'Medicines', 177, '', 'ti-pill', '15S', false, 1),
  (gen_random_uuid(), 'ZIFI DROPS 10ML', '', 'Cold & Flu', 89, '', 'ti-bottle', '10ML', false, 4),
  (gen_random_uuid(), 'SETFLOW SYP - 200 ML', '', 'Medicines', 263, '', 'ti-pill', '200 ML', false, 3),
  (gen_random_uuid(), 'KOFAREST DROPS 15ML', '', 'Cold & Flu', 60, '', 'ti-bottle', '15ML', false, 1),
  (gen_random_uuid(), 'ROSUVASTIN 10MG STRIP OF 10 TABLETS', '', 'Medicines', 203, '', 'ti-pill', '10''S', false, 13),
  (gen_random_uuid(), 'LACTOMED SUSP 100ML', '', 'Medicines', 131, '', 'ti-pill', '100ML', false, 2),
  (gen_random_uuid(), 'AZIZOOM 500MG  - 3TAB', '', 'Medicines', 76, '', 'ti-pill', '3TAB', false, 9),
  (gen_random_uuid(), 'VITOMIN D3 400IU DROPS 30ML', '', 'Cold & Flu', 84, '', 'ti-bottle', '30ML', false, 4),
  (gen_random_uuid(), 'LOSAR H TAB 15`S', '', 'Medicines', 312, '', 'ti-pill', '15`S', false, 1),
  (gen_random_uuid(), 'ANOVATE OINT 20GM - 20GM', '', 'Medicines', 145, '', 'ti-pill', '20GM', false, 1),
  (gen_random_uuid(), 'SUCRAFIL O GEL 200ML', '', 'Pain Relief', 295, '', 'ti-pill', '200ML', false, 2),
  (gen_random_uuid(), 'PIOPAR 15MG STRIP OF 15 TABLETS', '', 'Medicines', 79, '', 'ti-pill', '15''S', false, 2),
  (gen_random_uuid(), 'FEBUGOOD 80MG TABLET 10''S', '', 'Medicines', 257, '', 'ti-pill', '10''S', false, 5),
  (gen_random_uuid(), 'UDAPA S 10/100MG STRIP OF 10 TABLETS', '', 'Medicines', 186, '', 'ti-pill', '10''S', false, 4),
  (gen_random_uuid(), 'LETPRO 2.5MG TABLET', '', 'Medicines', 157, '', 'ti-pill', '5''S', false, 2),
  (gen_random_uuid(), '1EX SYRUP - 100 ML', '', 'Cold & Flu', 103, '', 'ti-bottle', '100 ML', false, 1),
  (gen_random_uuid(), 'SOBISIS FORTE TAB 30TAB - 30 TAB', '', 'Medicines', 236, '', 'ti-pill', '30 TAB', false, 15),
  (gen_random_uuid(), 'AMLOKIND AT TAB - 15TAB', '', 'Medicines', 61, '', 'ti-pill', '15TAB', false, 3),
  (gen_random_uuid(), 'FEBURIC 80MG TABLET 15''S', '', 'Medicines', 404, '', 'ti-pill', '15''S', false, 2),
  (gen_random_uuid(), 'NEFROSAVE STRIP OF 15 TABLETS', '', 'Medicines', 259, '', 'ti-pill', '15''S', false, 4),
  (gen_random_uuid(), 'BEVON DROPS 15ML 15ML', '', 'Cold & Flu', 61, '', 'ti-bottle', '15ML', false, 1),
  (gen_random_uuid(), 'T MINIC COLD ORANGE FLAVOUR ORAL SYRUP 60 ML', '', 'Cold & Flu', 125, '', 'ti-bottle', '60ML', false, 1),
  (gen_random_uuid(), 'SAYFER DROPS - 15ML', '', 'Cold & Flu', 78, '', 'ti-bottle', '15ML', false, 1),
  (gen_random_uuid(), 'CLARINOVA 500MG STRIP OF 10 TABLETS', '', 'Medicines', 358, '', 'ti-pill', '10''S', false, 1),
  (gen_random_uuid(), 'BRO ZEDEX SF EXP SYP - 100 ML', '', 'Medicines', 188, '', 'ti-pill', '100 ML', false, 1),
  (gen_random_uuid(), 'SOLVIN COLD SYP 60ML', '', 'Cold & Flu', 88, '', 'ti-bottle', '60ML', false, 1),
  (gen_random_uuid(), 'NAPROSYN 250 + TAB - 15TAB', '', 'Medicines', 108, '', 'ti-pill', '15TAB', false, 1),
  (gen_random_uuid(), 'TELVAS 40MG - 15TAB', '', 'Medicines', 95, '', 'ti-pill', '15TAB', false, 1),
  (gen_random_uuid(), 'CILACAR 20MG TABS - 15TAB', '', 'Medicines', 333, '', 'ti-pill', '15TAB', false, 1),
  (gen_random_uuid(), 'NEFROSAVE FORTE TABLET 15''S', '', 'Medicines', 259, '', 'ti-pill', '15''S', false, 3),
  (gen_random_uuid(), 'IRIVISC EYE DROPS 10ML', '', 'Cold & Flu', 129, '', 'ti-bottle', '10ML', false, 2),
  (gen_random_uuid(), 'FEMITE NO BITE 1% BOTTLE OF 9ML SOLUTION', '', 'Medicines', 277, '', 'ti-pill', '9ML', false, 1),
  (gen_random_uuid(), 'ESTRAHEAL 2MG TAB  ESTRADIOL VALERATE  - 28TAB', '', 'Medicines', 431, '', 'ti-pill', '28TAB', false, 1),
  (gen_random_uuid(), 'SKINSHINE TUBE OF 30GM CREAM', '', 'Skin Care', 298, '', 'ti-spray', '30GM', false, 2),
  (gen_random_uuid(), 'SKINSHINE TUBE OF 15GM CREAM', '', 'Skin Care', 155, '', 'ti-spray', '15GM', false, 1),
  (gen_random_uuid(), 'ALLEGRA 120MG TAB 10``S 10`S', '', 'Medicines', 273, '', 'ti-pill', '10`S', false, 2),
  (gen_random_uuid(), 'NEO MERCAZOLE 5MG TABLET 120''S', '', 'Medicines', 304, '', 'ti-pill', '120 NO''S', false, 1),
  (gen_random_uuid(), 'THUJA OINTMENT 25 GM', '', 'Medicines', 80, '', 'ti-pill', '25GM', false, 2),
  (gen_random_uuid(), 'BAIDYANATH CHITRAKADI BATI - 80 TABLETS', '', 'Medicines', 95, '', 'ti-pill', '80BOTTLE', false, 1),
  (gen_random_uuid(), 'ZALIM LOTION 10ML', '', 'Skin Care', 33, '', 'ti-spray', '10ML', false, 2),
  (gen_random_uuid(), 'STIMULIV TABLET 60', '', 'Medicines', 179, '', 'ti-pill', '10 NO''S', false, 1),
  (gen_random_uuid(), 'TELVAS CT LS STRIP OF 10 TABLETS', '', 'Medicines', 85, '', 'ti-pill', '10''S', false, 1),
  (gen_random_uuid(), 'D RISE 60K CAP - 4`S', '', 'Medicines', 132, '', 'ti-pill', '4`S', false, 1),
  (gen_random_uuid(), 'RESPITREE - 6X SYP-100ML - 100ML', '', 'Medicines', 126, '', 'ti-pill', '100ML', false, 10),
  (gen_random_uuid(), 'CIPLADINE 5% OINT 10GM', '', 'Medicines', 36, '', 'ti-pill', '10GM', false, 2),
  (gen_random_uuid(), 'CIPLADINE 5% OINT 15GM', '', 'Medicines', 49, '', 'ti-pill', '15GM', false, 2),
  (gen_random_uuid(), 'CIPLADINE 7.5% SOLUTION 100ML', '', 'Medicines', 85, '', 'ti-pill', '100ML', false, 1),
  (gen_random_uuid(), 'VENTIMOX-CV 457 SYP - 30ML', '', 'Medicines', 140, '', 'ti-pill', '30ML', false, 2),
  (gen_random_uuid(), 'VENTIMOX-CV 375  10TAB  - 10  TAB', '', 'Medicines', 219, '', 'ti-pill', '10  TAB', false, 3),
  (gen_random_uuid(), 'VENTIMOX CV 625 10 TAB - 10TAB', '', 'Medicines', 65, '', 'ti-pill', '10TAB', false, 4),
  (gen_random_uuid(), 'V-GEST SR 200 TAB - 10T', '', 'Medicines', 311, '', 'ti-pill', '10T', false, 1),
  (gen_random_uuid(), 'CLEAR COLD STRIP OF 10 CAPSULES', '', 'Cold & Flu', 32, '', 'ti-bottle', '10''S', false, 9),
  (gen_random_uuid(), 'BILACREST M SUSPENSION - 60ML', '', 'Stationery', 130, '', 'ti-pill', '60ML', false, 3),
  (gen_random_uuid(), 'BUDAMATE TRANSCAPS 200 CAPSULE 10 NO''S', '', 'Medicines', 155, '', 'ti-pill', '10''S', false, 1),
  (gen_random_uuid(), 'SOVENTUS JR SYP 60ML', '', 'Medicines', 118, '', 'ti-pill', '60 ML', false, 1),
  (gen_random_uuid(), 'MYOTM TAB 10''S', '', 'Medicines', 266, '', 'ti-pill', '10''S', false, 2),
  (gen_random_uuid(), 'XSTAN H STRIP OF 15 TABLETS', '', 'Medicines', 80, '', 'ti-pill', '15''S', false, 1),
  (gen_random_uuid(), 'ON ACNE GEL - 20 GM', '', 'Pain Relief', 130, '', 'ti-pill', '20 GM', false, 1),
  (gen_random_uuid(), 'FAMLYVIT SYP - 200ML', '', 'Medicines', 141, '', 'ti-pill', '200ML', false, 2),
  (gen_random_uuid(), 'AARJE DERM CREAM-15GM - 15  GM', '', 'Skin Care', 84, '', 'ti-spray', '15  GM', false, 5),
  (gen_random_uuid(), 'ROSE WATER LIQUID 50ML', '', 'Medicines', 15, '', 'ti-pill', '50ML', false, 3),
  (gen_random_uuid(), 'ROSE WATER 100ML', '', 'Medicines', 21, '', 'ti-pill', '100ML', false, 3),
  (gen_random_uuid(), 'JINVAR ROSE WATER - 300ML', '', 'Medicines', 36, '', 'ti-pill', '300ML', false, 1),
  (gen_random_uuid(), 'HCQS 200MG STRIP OF 15 TABLETS', '', 'Medicines', 102, '', 'ti-pill', '15`S', false, 3),
  (gen_random_uuid(), 'RESTYL 0.25MG TABLET', '', 'Medicines', 35, '', 'ti-pill', '15 NO''S', false, 1),
  (gen_random_uuid(), 'ZIFI 200MG TABLET 10''S', '', 'Medicines', 104, '', 'ti-pill', '10''S', false, 4),
  (gen_random_uuid(), 'GLYCIPHAGE 500MG TAB 20`S', '', 'Medicines', 42, '', 'ti-pill', '20`S', false, 4),
  (gen_random_uuid(), 'PANTOCID HP KIT TAB 6''S', '', 'Medicines', 224, '', 'ti-pill', '6''S', false, 7),
  (gen_random_uuid(), 'BAIDYANATH NAGPUR PUNARNAVARISHTA (450ML) (PACK OF 2)', '', 'Medicines', 213, '', 'ti-pill', '450ML', false, 2),
  (gen_random_uuid(), 'ZIFI 100MG DRY SYP 30ML', '', 'Medicines', 77, '', 'ti-pill', '30ML', false, 1),
  (gen_random_uuid(), 'SINAREST DROP - 15ML', '', 'Cold & Flu', 118, '', 'ti-bottle', '15ML', false, 1),
  (gen_random_uuid(), 'CALAFID TAB - 10TAB', '', 'Medicines', 141, '', 'ti-pill', '10TAB', false, 10),
  (gen_random_uuid(), 'CAL-UP PLUS -10TAB - 10TAB', '', 'Medicines', 142, '', 'ti-pill', '10TAB', false, 5),
  (gen_random_uuid(), 'GLUCO ONE TEST STRIPS 25''S', '', 'Medicines', 465, '', 'ti-pill', '25''S', false, 1),
  (gen_random_uuid(), 'DYNAPAR QPS PLUS SOLUTION 30ML', '', 'Medicines', 339, '', 'ti-pill', '30ML', false, 1),
  (gen_random_uuid(), 'KUMARI ASAV LIQUID 450ML', '', 'Medicines', 205, '', 'ti-pill', '450ML', false, 1),
  (gen_random_uuid(), 'BECOCNX D3 STRIP OF 10 TABLETS', '', 'Medicines', 172, '', 'ti-pill', '10''S', false, 2),
  (gen_random_uuid(), 'HISTAFREE M TABLET', '', 'Medicines', 144, '', 'ti-pill', '10 NO''S', false, 4),
  (gen_random_uuid(), 'FLAVEDON MR TAB 10`S', '', 'Medicines', 180, '', 'ti-pill', '10`S', false, 1),
  (gen_random_uuid(), 'DAPARYL M 10/500MG STRIP OF 10 TABLETS', '', 'Medicines', 155, '', 'ti-pill', '10''S', false, 1),
  (gen_random_uuid(), 'COMBIFLAM TAB 20``S 20`S', '', 'Medicines', 57, '', 'ti-pill', '20`S', false, 6),
  (gen_random_uuid(), 'COED3 STRIP OF 8 CAPSULES', '', 'Medicines', 263, '', 'ti-pill', '8''S', false, 1),
  (gen_random_uuid(), 'ZEMPRED 4MG TABLET 10''S', '', 'Medicines', 60, '', 'ti-pill', '10''S', false, 1),
  (gen_random_uuid(), 'WINOLAP 5MG TABLET 10''S', '', 'Medicines', 149, '', 'ti-pill', '10''S', false, 7),
  (gen_random_uuid(), 'CHERICOF T SFSYRUP - 100ML', '', 'Cold & Flu', 122, '', 'ti-bottle', '100ML', false, 1),
  (gen_random_uuid(), 'MUCOMIX 600MG TABLET 10''S', '', 'Medicines', 217, '', 'ti-pill', '10''S', false, 1),
  (gen_random_uuid(), 'LUPITUSS BOTTLE OF 100ML SUSPENSION', '', 'Stationery', 179, '', 'ti-pill', '100ML', false, 1),
  (gen_random_uuid(), 'PREGAFEM SR 200 TABLET 10 NO''S', '', 'Medicines', 596, '', 'ti-pill', '10''S', false, 1),
  (gen_random_uuid(), 'I KOLD EYE DROPS 10ML', '', 'Cold & Flu', 65, '', 'ti-bottle', '10ML', false, 3),
  (gen_random_uuid(), 'GLYCOEX-80 VM FORTE - 10TAB', '', 'Medicines', 200, '', 'ti-pill', '10TAB', false, 3),
  (gen_random_uuid(), 'CLINCITOP GEL 20GM', '', 'Pain Relief', 57, '', 'ti-pill', '20GM', false, 1),
  (gen_random_uuid(), 'BD 2 ML SYRINGE', '', 'Medicines', 17, '', 'ti-pill', '0 NO''S', false, 10),
  (gen_random_uuid(), 'ULTRABRITE SKIN CREAM 25GM', '', 'Skin Care', 164, '', 'ti-spray', '25GM', false, 1),
  (gen_random_uuid(), 'FOLITAS 30''S', '', 'Medicines', 49, '', 'ti-pill', '30''S', false, 3),
  (gen_random_uuid(), 'ABD SUSP 10ML', '', 'Medicines', 19, '', 'ti-pill', '10ML', false, 5),
  (gen_random_uuid(), 'CLEARWAX EAR DROPS 10ML', '', 'Cold & Flu', 91, '', 'ti-bottle', '10ML', false, 2),
  (gen_random_uuid(), 'RD FLORA CAP - 10 CAP', '', 'Medicines', 80, '', 'ti-pill', '10 CAP', false, 5),
  (gen_random_uuid(), 'AMRUTANJAN AROMATIC BALM 8ML', '', 'Pain Relief', 42, '', 'ti-pill', '8ML', false, 2),
  (gen_random_uuid(), 'AMRUTANJAN MAHA STRONG PAIN RELIEF BALM BOTTLE OF 8 ML', '', 'Pain Relief', 45, '', 'ti-pill', '8ML', false, 1),
  (gen_random_uuid(), 'AMRUTANJAN STRONG 25GM', '', 'Medicines', 90, '', 'ti-pill', '25 G', false, 2),
  (gen_random_uuid(), 'MEDROL 8MG TAB 14`S', '', 'Medicines', 89, '', 'ti-pill', '14`S', false, 2),
  (gen_random_uuid(), 'EPTOIN 100MG BOTTLE OF 120 TABLETS', '', 'Medicines', 226, '', 'ti-pill', '120 NO''S', false, 1),
  (gen_random_uuid(), 'NUROKIND OD 1500MCG STRIP OF 20 TABLETS', '', 'Medicines', 193, '', 'ti-pill', '20 NO''S', false, 1),
  (gen_random_uuid(), 'MET XL T 25MG STRIP OF 20 TABLETS', '', 'Medicines', 353, '', 'ti-pill', '20''S', false, 1),
  (gen_random_uuid(), 'DESOWEN CREAM 10GM', '', 'Skin Care', 266, '', 'ti-spray', '10GM', false, 1),
  (gen_random_uuid(), 'K DOX STRIP OF 10 CAPSULES', '', 'Medicines', 121, '', 'ti-pill', '10''S', false, 1),
  (gen_random_uuid(), 'IMODIUM CAPSULE', '', 'Medicines', 16, '', 'ti-pill', '4`S', false, 3),
  (gen_random_uuid(), 'FLEXON TAB 15`S', '', 'Medicines', 35, '', 'ti-pill', '15`S', false, 3),
  (gen_random_uuid(), 'NUROKIND GOLD INJECTION 2ML', '', 'Medicines', 34, '', 'ti-pill', '2ML', false, 3),
  (gen_random_uuid(), 'AZTOR 20MG STRIP OF 15 TABLETS', '', 'Medicines', 210, '', 'ti-pill', '15''S', false, 2),
  (gen_random_uuid(), 'ASOMEX 2.5MG TAB', '', 'Medicines', 108, '', 'ti-pill', '0', false, 2),
  (gen_random_uuid(), 'FGL - ZANDU BALM 25 ML - NF3 - 120 (NEW LOGO)', '', 'Pain Relief', 118, '', 'ti-pill', '25ML', false, 3),
  (gen_random_uuid(), 'MENTHODEX PAIN BALM 100 GM', '', 'Pain Relief', 155, '', 'ti-pill', '100GM', false, 4),
  (gen_random_uuid(), 'RAI TEL - 100ML', '', 'Medicines', 120, '', 'ti-pill', '100ML', false, 2),
  (gen_random_uuid(), 'PILOVEER - 60 TAB - 60 TAB', '', 'Medicines', 275, '', 'ti-pill', '60 TAB', false, 1),
  (gen_random_uuid(), 'M-BRENTA TAB  -10TAB - 10TAB', '', 'Medicines', 225, '', 'ti-pill', '10TAB', false, 2),
  (gen_random_uuid(), 'JIN KOKAM SARBAT - 500 ML', '', 'Medicines', 125, '', 'ti-pill', '500 ML', false, 3),
  (gen_random_uuid(), 'KAPIVA WHEATGRASS JUICE 1L | AYURVEDIC JUICE FOR DETOXIFICATION | HIGH CHLOROPHYLL', '', 'Medicines', 468, '', 'ti-pill', '1L', false, 1),
  (gen_random_uuid(), 'EVALON CREAM 15GM', '', 'Skin Care', 524, '', 'ti-spray', '15GM', false, 1),
  (gen_random_uuid(), 'COS 3 DROPS - 30ML', '', 'Cold & Flu', 343, '', 'ti-bottle', '30ML', false, 1),
  (gen_random_uuid(), 'IVARIL BOTTLE OF 100ML SYRUP', '', 'Cold & Flu', 102, '', 'ti-bottle', '100ML', false, 1),
  (gen_random_uuid(), 'RA THERMOSEAL FRESH MINT TOOTHPAST 100GM', '', 'Medicines', 159, '', 'ti-pill', '100GM', false, 1),
  (gen_random_uuid(), 'ZAVACEF 200 LB TAB - 10TAB', '', 'Medicines', 141, '', 'ti-pill', '10TAB', false, 5),
  (gen_random_uuid(), 'NEOSPORIN POWDER 10GM 10GM', '', 'Vitamins', 107, '', 'ti-pill', '10GM', false, 1),
  (gen_random_uuid(), 'DESOADD 0.05% CREAM 15GM', '', 'Skin Care', 164, '', 'ti-spray', '15GM', false, 1),
  (gen_random_uuid(), 'APRIGLIM M 3MG TABLET 15''S', '', 'Medicines', 216, '', 'ti-pill', '15''S', false, 1),
  (gen_random_uuid(), 'GLIMESTAR PM 2MG STRIP OF 10 TABLETS', '', 'Medicines', 117, '', 'ti-pill', '10''S', false, 1),
  (gen_random_uuid(), 'TRETIN 0.025% CREAM 30GM', '', 'Skin Care', 211, '', 'ti-spray', '30GM', false, 1),
  (gen_random_uuid(), 'NEBZMART G PACKET OF 5*2ML SMARTULES', '', 'Medicines', 510, '', 'ti-pill', '2ML', false, 1),
  (gen_random_uuid(), 'LACTODEX PREMIUM 1 POWDER 400 G', '', 'Vitamins', 734, '', 'ti-pill', '400GM', false, 2),
  (gen_random_uuid(), 'BETADINE 5% CREAM 10GM', '', 'Skin Care', 40, '', 'ti-spray', '10GM', false, 3),
  (gen_random_uuid(), 'BRUFEN 400MG TABLET', '', 'Medicines', 26, '', 'ti-pill', '15`S', false, 2),
  (gen_random_uuid(), 'ESGIPYRIN TABLET 15''S', '', 'Medicines', 146, '', 'ti-pill', '15 NO''S', false, 1),
  (gen_random_uuid(), 'XITCH COOL LIME POWDER 75GM - 75 GM', '', 'Vitamins', 67, '', 'ti-pill', '75 GM', false, 3),
  (gen_random_uuid(), 'KUFMA RED COUGH CAP - 10CAP', '', 'Cold & Flu', 79, '', 'ti-bottle', '10CAP', false, 15),
  (gen_random_uuid(), 'ORASORE WHITENING T.P. -50GM - 50 G.', '', 'Medicines', 149, '', 'ti-pill', '50 G.', false, 1),
  (gen_random_uuid(), 'DICLOWIN PLUS MR TAB - 10TAB', '', 'Medicines', 122, '', 'ti-pill', '10TAB', false, 15),
  (gen_random_uuid(), 'KHATNIL SPRAY - 250ML', '', 'Medicines', 160, '', 'ti-pill', '250ML', false, 2),
  (gen_random_uuid(), 'ERANDEL OIL 400ML', '', 'Medicines', 215, '', 'ti-pill', '400ML', false, 1),
  (gen_random_uuid(), 'DOXYL 100MG STRIP OF 10 CAPSULES', '', 'Medicines', 75, '', 'ti-pill', '10''S', false, 5),
  (gen_random_uuid(), 'DOXY C CAPSULE 10', '', 'Medicines', 38, '', 'ti-pill', '10''S', false, 3),
  (gen_random_uuid(), 'GLYNAMIC M 0.5 TAB - 10TAB', '', 'Medicines', 50, '', 'ti-pill', '10TAB', false, 5),
  (gen_random_uuid(), 'GUMEX MOUTH PAINT 60ML', '', 'Pain Relief', 154, '', 'ti-pill', '60ML', false, 1),
  (gen_random_uuid(), 'MONCEL FX TAB 10''S', '', 'Medicines', 204, '', 'ti-pill', '10''S', false, 1),
  (gen_random_uuid(), 'DOXYVA TAB 10''S', '', 'Medicines', 88, '', 'ti-pill', '10''S', false, 3),
  (gen_random_uuid(), 'BIOVAS 80MG TABLET 10''S', '', 'Medicines', 433, '', 'ti-pill', '10''S', false, 3),
  (gen_random_uuid(), 'FEBUTEC 40MG STRIP OF 10 TABLETS', '', 'Medicines', 157, '', 'ti-pill', '10''S', false, 5),
  (gen_random_uuid(), 'ROKO 2MG CAPSULE', '', 'Medicines', 24, '', 'ti-pill', '10 NO''S', false, 10),
  (gen_random_uuid(), 'LIV 52 SYP - 200ML', '', 'Medicines', 234, '', 'ti-pill', '200ML', false, 1),
  (gen_random_uuid(), 'ROSETAB GOLD 10 CAP - 10CAP', '', 'Medicines', 141, '', 'ti-pill', '10CAP', false, 1),
  (gen_random_uuid(), 'ZENTEL SYP 10ML', '', 'Medicines', 19, '', 'ti-pill', '10ML', false, 3),
  (gen_random_uuid(), 'CLOPILET 75MG STRIP OF 15 TABLETS', '', 'Medicines', 107, '', 'ti-pill', '15`S', false, 1),
  (gen_random_uuid(), 'BETNESOL TAB 20`S 20`S', '', 'Medicines', 18, '', 'ti-pill', '20`S', false, 3),
  (gen_random_uuid(), 'ECOPROT CHOCOLATE POWDER 200GM', '', 'Vitamins', 420, '', 'ti-pill', '200GM', false, 1),
  (gen_random_uuid(), 'METROHEX PLUS TUBE OF 20GM GEL', '', 'Pain Relief', 128, '', 'ti-pill', '20GM', false, 1),
  (gen_random_uuid(), 'CLINFRESH FACE WASH 75ML', '', 'Skin Care', 99, '', 'ti-spray', '75ML', false, 5),
  (gen_random_uuid(), 'MIGRATREAT TABLET 10 NO''S', '', 'Medicines', 93, '', 'ti-pill', '10''S', false, 5),
  (gen_random_uuid(), 'FORGLYN CFC FREE BOTTLE OF 120 METERED DOSE INHALER', '', 'Medicines', 679, '', 'ti-pill', '120BOX', false, 1),
  (gen_random_uuid(), 'FORMOFLO 250MCG TRASNHALER 120MD 7.2GM', '', 'Medicines', 905, '', 'ti-pill', '120BOX', false, 1),
  (gen_random_uuid(), 'GLYCOMET GP 2MG TAB - 15`S', '', 'Medicines', 180, '', 'ti-pill', '15`S', false, 7),
  (gen_random_uuid(), 'DOLO 650MG TAB - 15`S', '', 'Medicines', 32, '', 'ti-pill', '15`S', false, 2),
  (gen_random_uuid(), 'DYTOR PLUS 10MG STRIP OF 15 TABLETS', '', 'Medicines', 111, '', 'ti-pill', '15 NO''S', false, 1),
  (gen_random_uuid(), 'NEXPRO RD 20MG CAPSULE', '', 'Medicines', 140, '', 'ti-pill', '10 NO''S', false, 2),
  (gen_random_uuid(), 'ECONORM SACHET OF 1GM POWDER', '', 'Vitamins', 71, '', 'ti-pill', '1GM', false, 10),
  (gen_random_uuid(), 'ETHIGLO SKIN WHITENING FACE WASH-70 ML', '', 'Skin Care', 260, '', 'ti-spray', '70ML', false, 2),
  (gen_random_uuid(), 'MCROTEL 20MG TABLET 10''S', '', 'Medicines', 32, '', 'ti-pill', '10''S', false, 3),
  (gen_random_uuid(), 'MACPROT CHOCOLATE FLAVOUR BOTTLE OF 200GM POWDER', '', 'Vitamins', 380, '', 'ti-pill', '200GM', false, 1),
  (gen_random_uuid(), 'CITAL UTI SYP 100ML', '', 'Medicines', 214, '', 'ti-pill', '100ML', false, 1),
  (gen_random_uuid(), 'OH D3 DROPS 30ML', '', 'Cold & Flu', 34, '', 'ti-bottle', '30ML', false, 1),
  (gen_random_uuid(), 'KOFAREST SYP 100ML', '', 'Medicines', 170, '', 'ti-pill', '100ML', false, 1),
  (gen_random_uuid(), 'BRACEON CERVICAL COLLAR M - MED', '', 'Medicines', 349, '', 'ti-pill', 'MED', false, 1),
  (gen_random_uuid(), 'BRACEON CERVICAL COLLAR  - SMALL', '', 'Medicines', 349, '', 'ti-pill', 'SMALL', false, 1),
  (gen_random_uuid(), 'REGESTRONE 5MG TABLET', '', 'Medicines', 58, '', 'ti-pill', '10''S', false, 3),
  (gen_random_uuid(), 'BANOCIDE FORTE TAB 30`S 30`S', '', 'Medicines', 54, '', 'ti-pill', '30`S', false, 1),
  (gen_random_uuid(), 'PAUSE MF TAB 10`S', '', 'Medicines', 523, '', 'ti-pill', '10`S', false, 1),
  (gen_random_uuid(), 'LACSOFT 12% CREAM 50GM', '', 'Skin Care', 245, '', 'ti-spray', '50GM', false, 2),
  (gen_random_uuid(), 'AUTRIN STRIP OF 30 CAPSULES', '', 'Medicines', 205, '', 'ti-pill', '30 NO''S', false, 1),
  (gen_random_uuid(), 'SELSUN SHAMPOO 120ML', '', 'Medicines', 435, '', 'ti-pill', '120ML', false, 1),
  (gen_random_uuid(), 'ENZOFLAM SV TABLET 10''S', '', 'Medicines', 172, '', 'ti-pill', '10''S', false, 1),
  (gen_random_uuid(), 'CETAPHIL CLEANSING AND MOISTURISING SYNDET SOAP - 75G', '', 'Skin Care', 225, '', 'ti-spray', '75GM', false, 2),
  (gen_random_uuid(), 'ENZOFLAM TABLET', '', 'Medicines', 172, '', 'ti-pill', '10 NO''S', false, 3),
  (gen_random_uuid(), 'TAXIM O 200MG TAB 10`S 10`S', '', 'Medicines', 104, '', 'ti-pill', '10`S', false, 2),
  (gen_random_uuid(), 'BI QUINOL STRIP OF 20 TABLETS', '', 'Medicines', 42, '', 'ti-pill', '20''S', false, 3),
  (gen_random_uuid(), 'PROTINEX VANILLA NUTRITION DRINK TIN OF 400 G', '', 'Medicines', 599, '', 'ti-pill', '400GM', false, 1),
  (gen_random_uuid(), 'PROTINEX VANILLA POWDER 250GM REFILL', '', 'Vitamins', 345, '', 'ti-pill', '250GM', false, 1),
  (gen_random_uuid(), 'ASCORIL EXPECTORANT 120 ML', '', 'Medicines', 165, '', 'ti-pill', '120ML', false, 1),
  (gen_random_uuid(), 'GABAXIA SR 75MG TABLET 10''S', '', 'Medicines', 191, '', 'ti-pill', '10''S', false, 1),
  (gen_random_uuid(), 'VITHOBA ROOTFIX PASTE - 40 G. - 40GM', '', 'Medicines', 31, '', 'ti-pill', '40GM', false, 6),
  (gen_random_uuid(), 'ALLEGRA M TABLET 10''S', '', 'Medicines', 301, '', 'ti-pill', '10''S', false, 1),
  (gen_random_uuid(), 'METHIMEZ 10MG TABLET 30''S', '', 'Medicines', 359, '', 'ti-pill', '30''S', false, 1),
  (gen_random_uuid(), 'WYSOLONE DT 5MG STRIP OF 15 TABLETS', '', 'Medicines', 11, '', 'ti-pill', '15''S', false, 3),
  (gen_random_uuid(), 'HIMCOLIN GEL 30GM', '', 'Pain Relief', 304, '', 'ti-pill', '30GM', false, 1),
  (gen_random_uuid(), 'ZEDEX SF COUGH SUSP 100ML', '', 'Cold & Flu', 197, '', 'ti-bottle', '100 ML', false, 1),
  (gen_random_uuid(), 'VOVERAN 1% EMULGEL 30GM', '', 'Pain Relief', 171, '', 'ti-pill', '30GM', false, 1),
  (gen_random_uuid(), 'NEOSPORIN ANTIBIOTIC OINTMENT 1X10G PCS', '', 'Medicines', 136, '', 'ti-pill', '1X10G PCS', false, 1),
  (gen_random_uuid(), 'DISPRIN REGULAR 325MG TABLET 10''S', '', 'Medicines', 7, '', 'ti-pill', '10 STRIP', false, 6),
  (gen_random_uuid(), 'TENIVA 20MG TABLET 20''S', '', 'Medicines', 237, '', 'ti-pill', '20''S', false, 1),
  (gen_random_uuid(), 'OROTAUCH-40MG -10 TAB - 10TAB', '', 'Medicines', 61, '', 'ti-pill', '10TAB', false, 5),
  (gen_random_uuid(), 'AARJEPAN DSR - 10 CAP - 10CAP', '', 'Medicines', 112, '', 'ti-pill', '10CAP', false, 60),
  (gen_random_uuid(), 'AARJEFEX - D -100ML - 100ML', '', 'Medicines', 108, '', 'ti-pill', '100ML', false, 5),
  (gen_random_uuid(), 'AARJE CAL D3- 15TAB - 15 TAB', '', 'Medicines', 75, '', 'ti-pill', '15 TAB', false, 10),
  (gen_random_uuid(), 'HERBOFLEX OIL - 100 ML', '', 'Medicines', 141, '', 'ti-pill', '100 ML', false, 1),
  (gen_random_uuid(), 'NEOTREAT POWDER   - 10GM', '', 'Vitamins', 70, '', 'ti-pill', '10GM', false, 5),
  (gen_random_uuid(), 'TELFRESH AM 40 TAB - 10TAB', '', 'Medicines', 111, '', 'ti-pill', '10TAB', false, 3),
  (gen_random_uuid(), 'CCM BOTTLE OF 30 TABLETS', '', 'Medicines', 562, '', 'ti-pill', '30 NO''S', false, 1),
  (gen_random_uuid(), 'OTEK AC NEO EAR DROPS 5ML 5ML', '', 'Cold & Flu', 82, '', 'ti-bottle', '5ML', false, 1)
ON CONFLICT (name) DO UPDATE 
SET category = EXCLUDED.category, price = EXCLUDED.price, unit = EXCLUDED.unit, stock = EXCLUDED.stock;
